import {useCallback,useEffect,useRef,useState} from 'react';
import type {Branch} from '@automaktab/contracts';
import {ApiError,request,useQuery} from './api.js';
import type {Session} from './api.js';
import {Brand,ErrorNotice,Field,Icon,Loading} from './components.js';
import {AnalyticsView,Funnels,Live,Overview,SchoolPage,Schools,SystemView} from './views.js';
import {BillingPagination,BillingSchoolSelect,BillingView,CommandRecovery,useBillingPages} from './billing.js';
import {changeFilter,currentPeriod,filterSearch,filtersForRoute,filtersFromUrl,routeFromPath} from './state.js';
import type {Filters,Route} from './state.js';
import './styles.css';
const navigation:{label:string;items:{route:Route;label:string;icon:string}[]}[]=[{label:'Nazorat',items:[{route:'overview',label:'Umumiy ko‘rinish',icon:'overview'},{route:'schools',label:'Avtomaktablar',icon:'schools'}]},{label:'Tahlil',items:[{route:'traffic',label:'Tashriflar',icon:'traffic'},{route:'acquisition',label:'Mijozlar yo‘li',icon:'traffic'},{route:'usage',label:'Foydalanish',icon:'activity'},{route:'learning',label:'O‘quv natijalari',icon:'activity'},{route:'funnels',label:'Funnel va maqsadlar',icon:'traffic'},{route:'journeys',label:'Harakatlar ketma-ketligi',icon:'traffic'},{route:'live',label:'Jonli hodisalar',icon:'live'}]},{label:'Platforma billing',items:[{route:'contracts',label:'Shartnomalar',icon:'billing'},{route:'invoices',label:'Invoicelar',icon:'billing'},{route:'payments',label:'Tushumlar va avans',icon:'billing'},{route:'reminders',label:'Eslatmalar',icon:'bell'}]},{label:'Tizim',items:[{route:'diagnostics',label:'Ma’lumot holati',icon:'activity'},{route:'audit',label:'Amallar tarixi',icon:'audit'}]}];
const descriptions:Record<Route,string>={overview:'Barcha maktablar, platforma tushumi va e’tibor talab qilayotgan holatlar.',schools:'Maktab → filial → hisoblash subyekti. Operatsion tahrirlar CRM’da.',traffic:'Sahifalar, tashrif manbalari va kampaniyalar.',acquisition:'Platformaga murojaatdan tasdiqlangan maktab mijozigacha.',usage:'Maktablar mahsulotdan qanday foydalanayotganini kuzating.',learning:'Tasdiqlangan o‘quv natijalari va alohida practice ko‘rinishi.',funnels:'Event ketma-ketliklari va versiyalangan konversiya ta’riflari.',journeys:'Tasdiqlangan bog‘lanishlar doirasidagi harakatlar ketma-ketligi.',live:'Yangi hodisalar snapshot va jonli ulanish orqali.',contracts:'Har bir maktab uchun alohida kelishuv va platforma tarifi.',invoices:'Hisoblash asosini ko‘rib chiqing; yopilgan original o‘zgarmaydi.',payments:'Olingan pulni qayd eting, qarzga taqsimlang va avansni ko‘ring.',reminders:'Kechikkan platforma qarzlari. Ko‘rilgan — to‘langan degani emas.',diagnostics:'Manba qamrovi, checkpoint, uzilish va yangilanish chegarasi.',audit:'Bajarilgan amallar, sabablari va o‘zgarmas moliyaviy tarix.'};
interface AuthConfig{environment:string;providerConfigured:boolean;authorizeUrl?:string;}
function Login({onSession,error:sessionError}:{onSession:(session:Session)=>void;error?:ApiError}){const query=useQuery<AuthConfig>('/auth/config');const [pending,setPending]=useState(false);const [error,setError]=useState<ApiError>();const signIn=async()=>{setPending(true);setError(undefined);try{onSession((await request<Session>('/auth/demo-session',{method:'POST',body:{}})).data);}catch(caught){setError(caught as ApiError);}finally{setPending(false);}};const config=query.result?.data;return <main className="login"><div className="login-content"><Brand/><div className="stack"><h1>Barcha avtomaktablar nazorati</h1><p className="muted prose">Maktablar faoliyati, foydalanish va Automaktab platforma hisob-kitobi — egasi uchun yagona panel.</p></div><section className="login-panel" aria-label="Tizimga kirish">{(error??sessionError??query.error)&&<ErrorNotice error={(error??sessionError??query.error)!}/ >}{query.loading&&!config?<Loading label="Kirish sozlamalari tekshirilmoqda"/>:config?.environment==='synthetic'?<><span className="environment-tag">Sintetik muhit · Namunaviy ma’lumot</span><p>Bu muhitdagi maktablar va moliyaviy qaydlar sinov uchun. Haqiqiy hisobga ta’sir qilmaydi.</p><button className="primary" disabled={pending} onClick={()=>{void signIn();}}>{pending?'Kirilmoqda…':'Sinov egasi sifatida kirish'}</button></>:config?.providerConfigured&&config.authorizeUrl?<><p>Faqat tasdiqlangan platforma egasi kirishi mumkin.</p><a className="primary login-link" href={config.authorizeUrl}>CRM hisobi orqali kirish</a></>:<><p>Kirish provayderi sozlanmagan yoki hozir javob bermayapti.</p><button onClick={query.reload}>Qayta tekshirish</button></>}</section><p className="helper">Maktablarning o‘quvchi to‘lovlari bilan platforma billingini aralashtirmaydi.</p></div></main>;}
function Nav({route,navigate}:{route:Route;navigate:(path:string)=>void}){return <nav aria-label="Asosiy bo‘limlar">{navigation.map(group=><div className="nav-group" key={group.label}><p className="nav-label">{group.label}</p>{group.items.map(item=><a key={item.route} className="nav-link" href={`/${item.route}`} aria-current={route===item.route?'page':undefined} onClick={event=>{if(event.ctrlKey||event.metaKey||event.shiftKey||event.altKey)return;event.preventDefault();navigate(`/${item.route}`);}}><Icon name={item.icon}/>{item.label}</a>)}</div>)}</nav>;}
function FilterBand({filters,session,onChange,onReset,onDenied,schoolTotals,version}:{schoolTotals:boolean;filters:Filters;session:Session;onChange:(key:keyof Filters,value:string)=>void;onReset:()=>void;onDenied:()=>void;version:number}){
 const period=currentPeriod();const branchScope=`${filters.environment}:${filters.companyId}`;const branches=useBillingPages<Branch>(filters.companyId&&!schoolTotals?`/schools/${encodeURIComponent(filters.companyId)}/branches?${filterSearch({...filters,branchId:''})}`:null,onDenied,version);const [retainedBranch,setRetainedBranch]=useState<{scope:string;branch:Branch}>();const currentBranch=branches.result?.data.items.find(branch=>branch.id===filters.branchId);const selectedBranch=currentBranch??(retainedBranch?.scope===branchScope&&retainedBranch.branch.id===filters.branchId?retainedBranch.branch:undefined);
 useEffect(()=>{if(currentBranch)setRetainedBranch({scope:branchScope,branch:currentBranch});},[branchScope,currentBranch]);const items=branches.result?.data.items??[];const options=selectedBranch&&!items.some(branch=>branch.id===selectedBranch.id)?[selectedBranch,...items]:items;const active=[filters.companyId,filters.branchId,filters.surface,filters.timezone!=='Asia/Tashkent',filters.from!==period.from||filters.to!==period.to].filter(Boolean).length;
 return <section className="filters" aria-label="Davr va maktab filtrlari"><Field id="filter-from" label="Boshlanish sanasi"><input id="filter-from" type="date" required value={filters.from} onChange={event=>onChange('from',event.target.value)}/></Field><Field id="filter-to" label="Tugash sanasi" helper="Bu sana davrga kirmaydi"><input id="filter-to" type="date" required value={filters.to} onChange={event=>onChange('to',event.target.value)}/></Field><BillingSchoolSelect id="filter-company" value={filters.companyId} onChange={value=>onChange('companyId',value)} filters={filters} onDenied={onDenied} version={version} required={false}/><div className="stack"><Field id="filter-branch" label="Filial"><select id="filter-branch" disabled={schoolTotals||!filters.companyId} value={filters.branchId} aria-busy={branches.loading} onChange={event=>onChange('branchId',event.target.value)}><option value="">Barcha filiallar</option>{filters.branchId&&!options.some(branch=>branch.id===filters.branchId)&&<option value={filters.branchId} disabled>Tanlangan filial nomi bu sahifada mavjud emas · {filters.branchId}</option>}{options.map(branch=><option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></Field>{filters.companyId&&!schoolTotals&&<>{branches.loading&&<p className="helper" role="status">Filiallar olinmoqda…</p>}{branches.error&&<ErrorNotice error={branches.error} retry={branches.reload}/ >}{!branches.loading&&!branches.error&&branches.result&&!items.length&&<p className="helper">Bu sahifada filiallar topilmadi.</p>}<BillingPagination query={branches} label="filiallar"/></>}</div><Field id="filter-surface" label="Mahsulot yuzasi"><select id="filter-surface" disabled={schoolTotals} value={filters.surface} onChange={event=>onChange('surface',event.target.value)}><option value="">Barcha yuzalar</option><option value="marketing">Marketing sayti</option><option value="tenant">Maktab CRM’i</option><option value="learning">O‘quvchi tizimi</option><option value="practice">Practice</option></select></Field><button onClick={onReset}>Tozalash</button><div className="filter-summary"><span>{active} ta qo‘shimcha filtr · Muhit: {session.environment==='synthetic'?'sintetik':'haqiqiy'} · Biznes vaqti: Toshkent</span><label className="row">Ko‘rsatish vaqti <select aria-label="Ko‘rsatish vaqt zonasi" value={filters.timezone} onChange={event=>onChange('timezone',event.target.value)}><option value="Asia/Tashkent">Asia/Tashkent</option><option value="UTC">UTC</option></select></label></div></section>;
}
export function App(){const [session,setSession]=useState<Session>();const [checking,setChecking]=useState(true);const [authError,setAuthError]=useState<ApiError>();const [location,setLocation]=useState(()=>({path:window.location.pathname,search:window.location.search}));const [version,setVersion]=useState(0);const [filterNotice,setFilterNotice]=useState('');const drawer=useRef<HTMLDialogElement>(null);const menuButton=useRef<HTMLButtonElement>(null);const pageTitle=useRef<HTMLHeadingElement>(null);const authStarted=useRef(false);
 const deny=useCallback(()=>{setSession(undefined);setAuthError(new ApiError('SESSION_EXPIRED','Sessiya tugadi. Qayta kiring.','',false));},[]);
 useEffect(()=>{if(authStarted.current)return;authStarted.current=true;const query=new URLSearchParams(window.location.search);const code=query.get('code'),state=query.get('state');const operation=code&&state?request<Session>('/auth/session',{method:'POST',body:{exchangeCode:code,state}}):request<Session>('/auth/session');operation.then(result=>{setSession(result.data);setAuthError(undefined);if(code){window.history.replaceState({},'',window.location.pathname);setLocation({path:window.location.pathname,search:''});}}).catch(caught=>{if((caught as ApiError).code!=='SESSION_EXPIRED')setAuthError(caught as ApiError);}).finally(()=>setChecking(false));},[]);
 useEffect(()=>{const pop=()=>{setLocation({path:window.location.pathname,search:window.location.search});drawer.current?.close();};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop);},[]);
 const {route,id}=routeFromPath(location.path);const scope=filtersFromUrl(location.search);const schoolTotals=['contracts','invoices','payments','reminders'].includes(route);const filters=filtersForRoute({...scope,environment:session?.environment??scope.environment},route);
 useEffect(()=>{if(!schoolTotals||!scope.branchId&&!scope.surface)return;const normalized=filterSearch(filters);window.history.replaceState({},'',`${location.path}?${normalized}`);setLocation({path:location.path,search:`?${normalized}`});},[schoolTotals,scope.branchId,scope.surface,location.path]);
 const navigate=useCallback((path:string)=>{const destination=new URL(path,window.location.origin);const existing=filtersFromUrl(window.location.search);const extra=destination.searchParams;let next={...existing};extra.forEach((value,key)=>{if(key in next)next=changeFilter(next,key as keyof Filters,value);});const search=filterSearch(next);window.history.pushState({},'',`${destination.pathname}?${search}`);setLocation({path:destination.pathname,search:`?${search}`});drawer.current?.close();requestAnimationFrame(()=>pageTitle.current?.focus());},[]);
 const change=(key:keyof Filters,value:string)=>{const next=changeFilter(filters,key,value);window.history.pushState({},'',`${location.path}?${filterSearch(next)}`);setLocation({path:location.path,search:`?${filterSearch(next)}`});setFilterNotice(key==='companyId'&&filters.branchId?'Maktab o‘zgardi; filial filtri tozalandi.':'');};
 const reset=()=>{const next={...filtersFromUrl(''),environment:session?.environment??'synthetic'};window.history.pushState({},'',`${location.path}?${filterSearch(next)}`);setLocation({path:location.path,search:`?${filterSearch(next)}`});setFilterNotice('Filtrlar joriy oyga qaytarildi.');};
 const logout=async()=>{if(!session)return;try{await request('/auth/session',{method:'DELETE',csrfToken:session.csrfToken});sessionStorage.removeItem(`automaktab.intent.${session.actorId}`);setSession(undefined);setAuthError(undefined);}catch(caught){setAuthError(caught as ApiError);}};
 if(checking)return <main className="login"><div className="login-content"><Brand/><Loading label="Sessiya tekshirilmoqda"/></div></main>;
 if(!session)return <Login error={authError} onSession={value=>{setSession(value);setAuthError(undefined);}}/>;
 const props={filters,session,onDenied:deny,navigate,version};const title=navigation.flatMap(group=>group.items).find(item=>item.route===route)?.label??'Umumiy ko‘rinish';
 return <><a className="skip-link" href="#main">Asosiy qismga o‘tish</a><div className="app-shell"><aside className="rail"><Brand/><Nav route={route} navigate={navigate}/><div className="rail-footer"><span>{session.displayName}</span><button onClick={()=>{void logout();}}>Chiqish</button><span className="muted">Platforma egasi nazorati</span></div></aside><main id="main" className="workspace"><header className="page-header"><div className="stack"><h1 tabIndex={-1} ref={pageTitle}>{title}</h1><p className="muted prose">{descriptions[route]}</p></div><div className="header-actions"><button className="mobile-menu" ref={menuButton} onClick={()=>drawer.current?.showModal()} aria-label="Bo‘limlar menyusini ochish"><Icon name="menu"/></button><span className="environment-tag">{session.environment==='synthetic'?'Namunaviy ma’lumot · Sintetik':'Haqiqiy muhit'}</span><button aria-label="Ma’lumotlarni yangilash" onClick={()=>setVersion(value=>value+1)}><Icon name="refresh"/></button></div></header>{authError&&<ErrorNotice error={authError}/>}<CommandRecovery session={session} onDenied={deny} onCommitted={()=>setVersion(value=>value+1)}/><FilterBand filters={filters} session={session} onChange={change} onReset={reset} onDenied={deny} schoolTotals={schoolTotals} version={version}/>{schoolTotals&&<p className="helper">Platforma billing jami maktab bo‘yicha. Filial va mahsulot yuzasi filtrlari bu bo‘limda qo‘llanmaydi.</p>}{filterNotice&&<p role="status" className="helper">{filterNotice}</p>}{filters.from>=filters.to?<div className="notice" role="alert">Tugash sanasi boshlanish sanasidan keyin bo‘lishi kerak.</div>:route==='overview'?<Overview {...props}/>:route==='schools'?id?<SchoolPage {...props} id={id}/>:<Schools {...props}/>:['traffic','acquisition','usage','learning','journeys'].includes(route)?<AnalyticsView {...props} route={route}/>:route==='funnels'?<Funnels {...props}/>:route==='live'?<Live {...props}/>:route==='diagnostics'||route==='audit'?<SystemView {...props} route={route}/>:<BillingView {...props} route={route} id={id} onCommitted={()=>setVersion(value=>value+1)}/>}<footer className="page-footer">Automaktab platformasi · UZS, butun so‘m · Billing vaqti Asia/Tashkent · O‘quvchi kurs to‘lovlari alohida</footer></main></div><dialog className="drawer" ref={drawer} aria-labelledby="nav-title" onClose={()=>menuButton.current?.focus()}><div className="row between"><h2 id="nav-title">Bo‘limlar</h2><button aria-label="Menyuni yopish" onClick={()=>drawer.current?.close()}><Icon name="close"/></button></div><Nav route={route} navigate={navigate}/><div className="rail-footer"><span>{session.displayName}</span><button onClick={()=>{drawer.current?.close();void logout();}}>Chiqish</button></div></dialog></>;
}
