import {useEffect,useState} from 'react';
import {ApiError,request} from './api.js';
import type {Envelope,Session} from './api.js';
export interface Intent{actorId:string;key:string;path:string;body:Record<string,unknown>;createdAt:string;state?:'committed'|'notCommitted';result?:unknown;}
const eventName='automaktab-command-state';
export const intentStorage=(actorId:string)=>`automaktab.intent.${actorId}`;
export function readIntent(actorId:string):Intent|undefined{try{const raw=sessionStorage.getItem(intentStorage(actorId));if(!raw)return;const value=JSON.parse(raw) as Intent;if(value.actorId!==actorId||!value.key||!value.path.startsWith('/billing/')||!value.body||typeof value.body!=='object')return;return value;}catch{return;}}
function changed(){window.dispatchEvent(new Event(eventName));}
export function clearIntent(actorId:string){sessionStorage.removeItem(intentStorage(actorId));changed();}
export function storeIntent(intent:Intent){try{sessionStorage.setItem(intentStorage(intent.actorId),JSON.stringify(intent));}catch{throw new ApiError('RECOVERY_UNAVAILABLE','Brauzer tiklash niyatini saqlay olmadi. Moliyaviy amal yuborilmadi.','',false);}changed();}
export function recordOutcome(actorId:string,key:string,state:'committed'|'notCommitted',result?:unknown):boolean{const intent=readIntent(actorId);if(!intent||intent.key!==key)return false;storeIntent({...intent,state,...(result!==undefined?{result}:{})});return true;}
export async function confirmIntentOutcome(session:Session,key:string){const response=await request<{state:string;result?:unknown}>(`/commands/${encodeURIComponent(key)}`);if(response.data.state==='committed'||response.data.state==='notCommitted')recordOutcome(session.actorId,key,response.data.state,response.data.result);return response.data;}
export async function discoverIntent(session:Session,signal?:AbortSignal):Promise<void>{const response=await request<{items:(Intent&{idempotencyKey?:string})[]}>('/commands?status=unresolved',{signal});if(signal?.aborted||readIntent(session.actorId))return;const item=response.data.items.find(value=>value.actorId===session.actorId&&value.path?.startsWith('/billing/')&&value.body&&(value.key||value.idempotencyKey));if(item)storeIntent({actorId:item.actorId,key:item.key??item.idempotencyKey!,path:item.path,body:item.body,createdAt:item.createdAt});}
export async function acknowledgeIntent(session:Session):Promise<void>{const intent=readIntent(session.actorId);if(!intent?.state)throw new ApiError('UNKNOWN_COMMAND','Noma’lum natijani yopish mumkin emas.','',false);const response=await request<{resolved:boolean;state:string}>(`/commands/${encodeURIComponent(intent.key)}/acknowledgments`,{method:'POST',body:{},csrfToken:session.csrfToken});if(response.data.resolved!==true||response.data.state!==intent.state)throw new ApiError('ACK_NOT_CONFIRMED','Server natija ko‘rilganini tasdiqlamadi.','',true);if(readIntent(session.actorId)?.key===intent.key)clearIntent(session.actorId);}
const statusCheckCodes=new Set(['UNKNOWN_COMMAND','INVALID_REQUEST','SESSION_EXPIRED','FOUNDER_REQUIRED','CSRF_FAILED','RESOURCE_NOT_FOUND','PREVIEW_STALE','REVERSAL_PREVIEW_STALE','CORRECTION_PREVIEW_STALE','ALLOCATION_CONFLICT','SOURCE_NOT_READY','BILLING_POLICY_UNCONFIRMED','CONTRACT_REVISION_CONFLICT','PERIOD_ALREADY_CLOSED','PREVIEW_EXPIRED','PREVIEW_NOT_FOUND','INSUFFICIENT_CREDIT','POLICY_STALE']);
export function useIntent(session:Session){const [intent,setIntent]=useState(()=>readIntent(session.actorId));useEffect(()=>{const update=()=>setIntent(readIntent(session.actorId));window.addEventListener(eventName,update);window.addEventListener('storage',update);return()=>{window.removeEventListener(eventName,update);window.removeEventListener('storage',update);};},[session.actorId]);return intent;}
export function useFinancialCommand(session:Session,onCommitted:()=>void){const intent=useIntent(session);const [busy,setBusy]=useState(false);const [error,setError]=useState<ApiError>();const [result,setResult]=useState<Envelope<unknown>>();const [rejectedPreview,setRejectedPreview]=useState<string>();
 const commit=async(path:string,body:Record<string,unknown>)=>{if(readIntent(session.actorId)){setError(new ApiError('UNKNOWN_COMMAND','Oldingi amal natijasini yuqoridagi tiklash panelidan aniqlang yoki ko‘rilgan deb tasdiqlang.','',false));return false;}const next:Intent={actorId:session.actorId,key:crypto.randomUUID(),path,body,createdAt:new Date().toISOString()};setBusy(true);setError(undefined);setResult(undefined);try{storeIntent(next);const response=await request(path,{method:'POST',body,key:next.key,csrfToken:session.csrfToken});recordOutcome(session.actorId,next.key,'committed',response.data);setResult(response);onCommitted();try{await acknowledgeIntent(session);}catch{setError(new ApiError('ACK_NOT_CONFIRMED','Amal bajarilgan. Natija ko‘rilganini serverga tasdiqlash kelmadi; tiklash panelida qayta tasdiqlang.','',true));}return true;}catch(caught){const apiError=caught as ApiError;setError(apiError);if(['PREVIEW_STALE','REVERSAL_PREVIEW_STALE','CORRECTION_PREVIEW_STALE','ALLOCATION_CONFLICT','CONTRACT_REVISION_CONFLICT','PREVIEW_EXPIRED'].includes(apiError.code))setRejectedPreview(String(body.expectedPreviewHash??body.expectedReversalPreviewHash??''));if(statusCheckCodes.has(apiError.code)){try{const status=await confirmIntentOutcome(session,next.key);if(status.state==='committed')onCommitted();}catch{ /* a failed status read cannot prove non-commit */ }}return false;}finally{setBusy(false);}};
 return {busy,error,result,intent,blocked:Boolean(intent),commit,rejectsPreview:(hash:string)=>hash===rejectedPreview,clearResult:()=>{setResult(undefined);setError(undefined);setRejectedPreview(undefined);}};
}
