import {cloneElement,isValidElement} from 'react';
import type {ReactNode} from 'react';
import type {ApiError,Meta,QueryState} from './api.js';
import {dateText,moneyText,numberText,statusLabels} from './state.js';
export function Icon({name}:{name:string}){const paths:Record<string,string>={overview:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',schools:'M3 21h18 M5 21V5l7-3 7 3v16 M9 8h1 M14 8h1 M9 12h1 M14 12h1 M10 21v-5h4v5',traffic:'M3 20V4 M3 20h18 M7 15l4-5 4 3 6-8',billing:'M6 3h12v18l-3-2-3 2-3-2-3 2z M9 7h6 M9 11h6 M9 15h3',activity:'M2 12h5l3-8 4 16 3-8h5',audit:'M9 3H5v18h14V7l-4-4H9 M9 10h6 M9 14h6 M9 18h3',bell:'M5 17h14l-2-3V9a5 5 0 0 0-10 0v5z M10 20h4',menu:'M4 6h16 M4 12h16 M4 18h16',check:'M5 12l4 4L19 6',warning:'M12 3 2 21h20z M12 9v5 M12 17h.01',close:'M6 6l12 12 M18 6 6 18',arrow:'M5 12h14 M14 7l5 5-5 5',refresh:'M20 7v5h-5 M4 17v-5h5 M6 7a7 7 0 0 1 12-1l2 6 M4 12l2 6a7 7 0 0 0 12-1',search:'M21 21l-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',live:'M12 12h.01 M8 8a6 6 0 0 0 0 8 M16 8a6 6 0 0 1 0 8 M5 5a10 10 0 0 0 0 14 M19 5a10 10 0 0 1 0 14'};return <svg className="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]??paths.traffic}/></svg>;}
export function Brand(){return <div className="brand"><svg className="brand-mark" viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="M5 25 14 7h4l9 18M9 18h14M12 25l4-8 4 8" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg><span>Automaktab<span className="helper" style={{display:'block'}}>Analytics</span></span></div>;}
export function Badge({status,label}:{status:string;label?:string}){const kind=['active','fresh','paid','committed'].includes(status)?'success':['overdue','error','denied'].includes(status)?'danger':['stale','partial','unknown','suspended','pending'].includes(status)?'warning':'info';return <span className={`badge ${kind}`}>{label??statusLabels[status]??status}</span>;}
export function DataStatus({meta,timezone}:{meta:Meta;timezone?:string}){return <div className="data-status"><Icon name={meta.status==='fresh'?'check':'warning'}/><div><strong>{statusLabels[meta.status??'unknown']??'Noma’lum'}</strong><span> · Ma’lumot {dateText(meta.dataThrough,timezone)} gacha</span>{meta.coverageFrom&&<span> · Qamrov {dateText(meta.coverageFrom,timezone)} dan</span>}{meta.warnings?.length? <ul className="blockers">{meta.warnings.map((warning,index)=><li key={index}>{warning}</li>)}</ul>:null}</div></div>;}
export function ErrorNotice({error,retry}:{error:ApiError;retry?:()=>void}){return <div className="notice stack" role="alert"><div className="row error-text"><Icon name="warning"/><strong>{error.message}</strong></div>{error.requestId&&<p className="helper">So‘rov: <span className="monospace">{error.requestId}</span></p>}{retry&&<div><button onClick={retry}>Qayta tekshirish</button></div>}</div>;}
export function Loading({label='Ma’lumotlar olinmoqda'}:{label?:string}){return <div className="loading-state" role="status"><p className="muted">{label}…</p><div className="loading-line"/><div className="loading-line"/><div className="loading-line"/></div>;}
export function Empty({title='Tanlangan davrda ma’lumot yo‘q',children,action}:{title?:string;children?:ReactNode;action?:ReactNode}){return <div className="empty-state"><h3>{title}</h3><p>{children??'Manba ulanganidan va tanlangan filtrlar to‘g‘riligidan so‘ng bu yerda ma’lumot ko‘rinadi.'}</p>{action}</div>;}
export function QueryBoundary<T>({query,children}:{query:QueryState<T>&{reload:()=>void};children:(data:T,meta:Meta)=>ReactNode}){if(!query.result)return query.error?<ErrorNotice error={query.error} retry={query.reload}/>:<Loading/>;return <>{query.error&&<ErrorNotice error={query.error} retry={query.reload}/ >}{query.loading&&<p role="status" className="helper">Shu filtrlar bo‘yicha yangilanmoqda; oldingi natija ko‘rsatilgan.</p>}{children(query.result.data,query.result.meta)}</>;}
export function Panel({title,action,children}:{title:string;action?:ReactNode;children:ReactNode}){return <section className="panel"><div className="panel-heading"><h2>{title}</h2>{action}</div>{children}</section>;}
export function Table({caption,headers,children}:{caption:string;headers:string[];children:ReactNode}){return <div className="table-wrap" tabIndex={0} aria-label={`${caption}, gorizontal aylantirish mumkin`}><table><caption>{caption}</caption><thead><tr>{headers.map(header=><th key={header} scope="col">{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;}
export interface Metric{key:string;label:string;value:string|number|null;unit:string;definitionVersion?:string;availability?:string;description?:string;}
const metricLabels:Record<string,string>={schools:'Maktablar',activeStudents:'Faol o‘quvchilar',collected:'Kelgan tushum',outstanding:'Qoldiq qarz',overdue:'Muddati o‘tgan qarz',credit:'Maktab avansi va krediti',events:'Hodisalar',visitors:'Tashrif buyuruvchilar',sessions:'Sessiyalar',pageviews:'Sahifa ko‘rishlar',leads:'Murojaatlar',conversions:'Mijozga aylanganlar',completion:'Bitirish ko‘rsatkichi',billed:'Hisoblangan summa'};
export function Metrics({metrics}:{metrics:Metric[]}){if(!metrics.length)return <Empty title="Ko‘rsatkichlar hali mavjud emas"/>;return <div className="metrics">{metrics.map(metric=><div className="metric" key={metric.key}><span className="metric-label">{metricLabels[metric.key]??metric.label}</span><strong className="metric-value number">{metric.availability==='unknown'||metric.value===null?'Ma’lumot yo‘q':metric.unit==='UZS'||metric.unit==='money'?moneyText(String(metric.value)):numberText(metric.value)}</strong><span className="metric-meta">{metric.description??(metric.unit==='UZS'||metric.unit==='money'?'Automaktab platformasi':metric.unit==='percent'?'foiz':metric.unit==='count'?'soni':metric.unit)}{metric.definitionVersion&&` · ta’rif ${metric.definitionVersion}`}</span></div>)}</div>;}
export function Field({label,id,helper,children,error}:{label:string;id:string;helper?:string;children:ReactNode;error?:string}){const control=isValidElement<{'aria-describedby'?:string;'aria-invalid'?:boolean}>(children)?cloneElement(children,{'aria-describedby':[children.props['aria-describedby'],helper?`${id}-helper`:undefined,error?`${id}-error`:undefined].filter(Boolean).join(' ')||undefined,'aria-invalid':error?true:children.props['aria-invalid']}):children;return <div className="field"><label htmlFor={id}>{label}</label>{control}{helper&&<span id={`${id}-helper`} className="helper">{helper}</span>}{error&&<span className="error-text" id={`${id}-error`}>{error}</span>}</div>;}
