import {test,expect,type Page,type Route} from '@playwright/test';

const fixtureMeta={requestId:'synthetic-billing-pages',apiVersion:1,status:'fresh'};
const fixtureSession={actorId:'synthetic-ui-owner',displayName:'Sintetik egasi',csrfToken:'synthetic-csrf',environment:'synthetic'};
function reply(data:unknown){return {status:200,contentType:'application/json',body:JSON.stringify({data,meta:fixtureMeta})};}
function school(id:string){return {id,name:`Sintetik maktab ${id.replace('school-','')}`,status:'active',activeStudents:1,branchesCount:0,branches:[]};}
async function stubFounder(page:Page){await page.context().route('**/api/v1/auth/session',route=>route.fulfill(reply(fixtureSession)));}

test('editing a financial input invalidates a late preview response',async({page})=>{
 const meta={requestId:'synthetic-preview-race',apiVersion:1,status:'fresh'};
 const reply=(data:unknown)=>({status:200,contentType:'application/json',body:JSON.stringify({data,meta})});
 await page.route('**/api/v1/billing/policy-status',route=>route.fulfill(reply({status:'active',revisionId:'synthetic-policy',policyHash:'hash',policy:{}})));
 await page.route('**/api/v1/billing/contracts?*',route=>route.fulfill(reply({items:[]})));
 let receive!:(route:Route)=>void;const pending=new Promise<Route>(resolve=>{receive=resolve;});
 await page.route('**/api/v1/billing/contract-previews',route=>{receive(route);});
 await page.goto('/contracts?companyId=synthetic-school-2');await page.getByRole('button',{name:'Sinov egasi sifatida kirish'}).click();
 await page.locator('#contract-company').selectOption('synthetic-school-2');await page.locator('#contract-amount').fill('100000');
 await page.getByRole('button',{name:'Server reviewini olish',exact:true}).click();const oldRoute=await pending;
 const completed=Promise.race([page.waitForEvent('requestfinished',request=>request===oldRoute.request()),page.waitForEvent('requestfailed',request=>request===oldRoute.request())]);
 await page.locator('#contract-amount').fill('200000');
 await oldRoute.fulfill(reply({previewId:'old-preview',previewHash:'old-hash',ledgerRevision:'1',expiresAt:'2099-01-01T00:00:00Z',canCommit:true,blockers:[],input:{action:'create',amountMinor:'100000'},consequences:{contract:{id:'old-contract',amountMinor:'100000'}}})).catch(()=>undefined);
 await completed;await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));
 await expect(page.locator('#contract-amount')).toHaveValue('200000');
 await expect(page.getByRole('heading',{name:'Kelishuv oqibatlarini tasdiqlang'})).toHaveCount(0);
 await expect(page.getByRole('button',{name:'Server reviewini olish',exact:true})).toBeEnabled();
});

for(const discovery of ['lost','racing'] as const)test(`${discovery} initial discovery recovers the older intent after the rejected new key has GET proof and ACK`,async({page})=>{
 await stubFounder(page);const context=page.context();const oldIntent={actorId:fixtureSession.actorId,key:'old-server-key',path:'/billing/payments',body:{companyId:'school-52',amount:{currency:'UZS',minor:'100000'}},createdAt:'2026-10-01T00:00:00Z'};
 await context.route('**/api/v1/schools?*',route=>route.fulfill(reply({items:[school('school-52')],nextCursor:null})));
 await context.route('**/api/v1/schools/school-52?*',route=>route.fulfill(reply(school('school-52'))));
 await context.route('**/api/v1/billing/policy-status',route=>route.fulfill(reply({status:'active',revisionId:'policy',policyHash:'hash',policy:{}})));
 for(const resource of ['contracts','payments','school-credits','credits'])await context.route(`**/api/v1/billing/${resource}?*`,route=>route.fulfill(reply({items:[],nextCursor:null})));
 await context.route('**/api/v1/billing/contract-previews',route=>route.fulfill(reply({previewId:'review',previewHash:'hash',ledgerRevision:'1',expiresAt:'2099-01-01T00:00:00Z',canCommit:true,blockers:[],input:{action:'create',companyId:'school-52',amountMinor:'100000'},consequences:{companyId:'school-52',amountMinor:'100000'}})));
 let rejectedKey='',discoveryCount=0,acknowledged=false;let initialRoute:Route|undefined;let statusReceived!:(route:Route)=>void;const statusPending=new Promise<Route>(resolve=>{statusReceived=resolve;});
 await context.route('**/api/v1/commands?*',route=>{discoveryCount++;if(discoveryCount===1){if(discovery==='lost')return route.abort('failed');initialRoute=route;return;}return route.fulfill(reply({items:[oldIntent],nextCursor:null}));});
 await context.route('**/api/v1/commands/*',route=>{const key=new URL(route.request().url()).pathname.split('/').at(-1);if(key===rejectedKey){statusReceived(route);return;}return route.fulfill(reply({state:'unknown'}));});
 await context.route('**/api/v1/commands/*/acknowledgments',route=>{expect(new URL(route.request().url()).pathname).toContain(rejectedKey);acknowledged=true;return route.fulfill(reply({resolved:true,state:'notCommitted'}));});
 await context.route('**/api/v1/billing/contracts',route=>{rejectedKey=route.request().headers()['idempotency-key']!;expect(rejectedKey).toBeTruthy();return route.fulfill({status:409,json:{error:{code:'UNKNOWN_COMMAND',message:'Oldingi niyat hal qilinmagan.',retryable:false},meta:fixtureMeta}});});
 await page.goto('/contracts?companyId=school-52');await expect(page.locator('#contract-company')).toHaveValue('school-52');await page.locator('#contract-amount').fill('100000');await page.getByRole('button',{name:'Server reviewini olish',exact:true}).click();await page.getByRole('region',{name:'Kelishuv oqibatlarini tasdiqlang',exact:true}).getByRole('button',{name:'Tasdiqlash',exact:true}).click();
 const statusRoute=await statusPending;const recovery=page.getByRole('region',{name:'Moliyaviy amal natijasini tiklash'});await expect(recovery).toContainText(rejectedKey);await expect(recovery.getByRole('heading',{name:'Oldingi amal natijasini aniqlang'})).toBeVisible();await expect(recovery.getByRole('button',{name:'Natijani ko‘rdim — tasdiqlash'})).toHaveCount(0);
 if(initialRoute)await initialRoute.fulfill(reply({items:[oldIntent]})).catch(()=>undefined);await expect(recovery).toContainText(rejectedKey);
 await statusRoute.fulfill(reply({state:'notCommitted',code:'UNKNOWN_COMMAND'}));await expect(recovery.getByRole('heading',{name:'Amal bajarilmagan'})).toBeVisible();expect(acknowledged).toBe(false);
 await recovery.getByRole('button',{name:'Natijani ko‘rdim — tasdiqlash'}).click();await expect(recovery).toContainText(oldIntent.key);expect(acknowledged).toBe(true);await expect(recovery.getByRole('heading',{name:'Oldingi amal natijasini aniqlang'})).toBeVisible();
 const newTab=await context.newPage();await newTab.goto('/payments?companyId=school-52');await expect(newTab.getByRole('region',{name:'Moliyaviy amal natijasini tiklash'})).toContainText(oldIntent.key);await expect(newTab.getByRole('button',{name:'Taqsimot taklifini olish'})).toBeDisabled();await newTab.close();
});

async function stubBillingPages(page:Page){
 await stubFounder(page);const context=page.context();const schools=Array.from({length:52},(_,index)=>school(`school-${index+1}`));const contracts=schools.map((_,index)=>({id:`contract-${index+1}`,companyId:'school-52',planType:'fixed_monthly',amountMinor:String((index+1)*100),currency:'UZS',businessTimezone:'Asia/Tashkent',effectiveFrom:'2026-10-01',effectiveTo:null,revision:1,status:'active',policyRevisionId:'policy'}));
 const invoices=schools.map((_,index)=>({id:`invoice-${index+1}`,companyId:'school-52',contractId:`contract-${index+1}`,contractRevision:1,kind:'subscription',periodStart:'2026-10-01',periodEnd:'2026-11-01',currency:'UZS',totalMinor:'100',correctedTotalMinor:'100',outstandingMinor:'100',dueDate:'2026-11-08',closedAt:'2026-10-01T00:00:00Z',lines:[],previewHash:'hash',canClose:false,blockers:[],policyRevisionId:'policy',sourceCheckpoint:'checkpoint'}));
 const payments=schools.map((_,index)=>({id:`payment-${index+1}`,companyId:'school-52',amount:{currency:'UZS',minor:'200'},receivedAt:'2026-10-08T00:00:00Z',method:'bank_transfer',reference:null,allocatedMinor:'0',unallocatedMinor:'200',reversed:false,allocations:[]}));const reminders=invoices.map((invoice,index)=>({id:`reminder-${index+1}`,companyId:'school-52',invoiceId:invoice.id,amountMinor:'100',dueDate:'2026-10-01',overdueDays:7,acknowledged:false}));
 await context.route('**/api/v1/commands?*',route=>route.fulfill(reply({items:[]})));
 await context.route('**/api/v1/schools?*',route=>{const query=new URL(route.request().url()).searchParams;expect(query.get('limit')).toBe('50');const filtered=schools.filter(item=>item.name.includes(query.get('search')??''));const offset=query.get('cursor')?50:0;return route.fulfill(reply({items:filtered.slice(offset,offset+50),nextCursor:filtered.length>offset+50?'school-50':null}));});
 await context.route('**/api/v1/schools/school-*?*',route=>route.fulfill(reply(school(new URL(route.request().url()).pathname.split('/').at(-1)!))));
 await context.route('**/api/v1/billing/policy-status',route=>route.fulfill(reply({status:'active',revisionId:'policy',policyHash:'hash',policy:{}})));
 for(const [resource,items]of Object.entries({'billing/contracts':contracts,'billing/invoices':invoices,'billing/payments':payments,reminders}))await context.route(`**/api/v1/${resource}?*`,route=>{const query=new URL(route.request().url()).searchParams;expect(query.get('limit')).toBe('50');expect(query.has('branchId')).toBe(false);expect(query.has('surface')).toBe(false);const offset=query.get('cursor')?50:0;return route.fulfill(reply({items:items.slice(offset,offset+50),nextCursor:items.length>offset+50?'page-50':null}));});
 await context.route('**/api/v1/billing/credits?*',route=>{const query=new URL(route.request().url()).searchParams;expect(query.get('limit')).toBe('50');const items=schools.filter(item=>!query.get('companyId')||item.id===query.get('companyId')).map(item=>({companyId:item.id,unallocatedMinor:'200',receiptCreditMinor:'200',nonCashCreditMinor:'0'}));const offset=query.get('cursor')?50:0;return route.fulfill(reply({items:items.slice(offset,offset+50),nextCursor:items.length>offset+50?'school-50':null}));});
 await context.route('**/api/v1/billing/school-credits?*',route=>route.fulfill(reply({items:[],nextCursor:null})));
}

test('owner traverses later billing rows and required selectors retain a real later school and contract',async({page})=>{
 await stubBillingPages(page);await page.goto('/contracts?companyId=school-52&branchId=ignored&surface=tenant');
 const form=page.locator('form').filter({has:page.locator('#contract-company')});await expect(page.locator('#contract-company option:checked')).toHaveText('Sintetik maktab 52');
 await form.getByRole('button',{name:'Keyingi maktablar'}).click();await page.locator('#contract-company').selectOption('school-51');await form.getByRole('button',{name:'Oldingi maktablar'}).click();await expect(page.locator('#contract-company')).toHaveValue('school-51');await expect(page.locator('#contract-company option:checked')).toHaveText('Sintetik maktab 51');
 await page.locator('#contract-company-search').fill('maktab 52');await expect(page.locator('#contract-company option[value="school-52"]')).toHaveCount(1);await page.locator('#contract-company').selectOption('school-52');await page.locator('#contract-company-search').fill('');await expect(page.locator('#contract-company option:checked')).toHaveText('Sintetik maktab 52');
 const contracts=page.locator('section.panel').filter({has:page.getByRole('heading',{name:'Maktab shartnomalari',exact:true})});await expect(contracts.getByRole('row')).toHaveCount(51);await contracts.getByRole('button',{name:'Keyingi shartnomalar',exact:true}).click();await expect(contracts.getByRole('row')).toHaveCount(3);await contracts.getByRole('button',{name:'Oldingi shartnomalar',exact:true}).click();await expect(contracts.getByRole('row')).toHaveCount(51);
 await page.getByRole('link',{name:'Invoicelar',exact:true}).first().click();await page.getByRole('button',{name:'Keyingi shartnoma variantlari'}).click();await page.locator('#invoice-contract').selectOption('contract-52');await page.getByRole('button',{name:'Oldingi shartnoma variantlari'}).click();await expect(page.locator('#invoice-contract')).toHaveValue('contract-52');await expect(page.locator('#invoice-contract option[value="contract-52"]')).toHaveCount(1);
 const invoices=page.locator('section.panel').filter({has:page.getByRole('heading',{name:'Invoicelar',exact:true})});await invoices.getByRole('button',{name:'Keyingi invoicelar'}).click();await expect(invoices.getByRole('link',{name:'invoice-52',exact:true})).toBeVisible();await expect(invoices.getByRole('button',{name:'Keyingi invoicelar'})).toBeDisabled();
 await page.getByRole('region',{name:'Davr va maktab filtrlari'}).getByRole('button',{name:'Keyingi maktablar'}).click();await page.locator('#filter-company').selectOption('school-51');await expect(page.locator('#invoice-contract')).toHaveValue('');await expect(invoices.getByRole('link',{name:'invoice-1',exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Eslatmalar',exact:true}).first().click();const reminders=page.locator('section.panel').filter({has:page.getByRole('heading',{name:'Muddati o‘tgan platforma hisoblari',exact:true})});await reminders.getByRole('button',{name:'Keyingi eslatmalar'}).click();await expect(reminders.getByText('invoice-52',{exact:true})).toBeVisible();await reminders.getByRole('button',{name:'Oldingi eslatmalar'}).click();await expect(reminders.getByText('invoice-1',{exact:true})).toBeVisible();
});

test('receipt allocations survive invoice pages and are reviewed together without posting',async({page})=>{
 await stubBillingPages(page);let reviewed:unknown;await page.context().route('**/api/v1/billing/payments/payment-52/allocation-previews',route=>{const input=route.request().postDataJSON() as {allocations:{invoiceId:string;amountMinor:string}[]};reviewed=input.allocations;return route.fulfill(reply({previewId:'allocation-review',previewHash:'hash',ledgerRevision:'1',expiresAt:'2099-01-01T00:00:00Z',canCommit:true,blockers:[],input,consequences:{allocations:input.allocations,unallocatedMinor:'170'}}));});
 await page.goto('/payments?companyId=school-52');await expect(page.locator('#payment-company option:checked')).toHaveText('Sintetik maktab 52');const history=page.locator('section.panel').filter({has:page.getByRole('heading',{name:'Tushumlar tarixi',exact:true})});await history.getByRole('button',{name:'Keyingi tushumlar'}).click();await history.getByRole('row').filter({hasText:'payment-52'}).getByRole('button',{name:'Avansni taqsimlash'}).click();
 await page.getByLabel('invoice-1 avans taqsimoti',{exact:true}).fill('10');await page.getByRole('button',{name:'Keyingi taqsimot invoicelari'}).click();await page.getByLabel('invoice-51 avans taqsimoti',{exact:true}).fill('20');await page.getByRole('button',{name:'Oldingi taqsimot invoicelari'}).click();await expect(page.getByLabel('invoice-1 avans taqsimoti',{exact:true})).toHaveValue('10');
 await page.getByRole('button',{name:'Taqsimotni review qilish',exact:true}).click();const review=page.getByRole('region',{name:'Avans taqsimoti oqibatlari',exact:true});await expect(review.getByText('invoice-1',{exact:true})).toBeVisible();await expect(review.getByText('invoice-51',{exact:true})).toBeVisible();expect(reviewed).toEqual([{invoiceId:'invoice-1',amountMinor:'10'},{invoiceId:'invoice-51',amountMinor:'20'}]);
 await page.getByRole('button',{name:'Qoldiq kiritish',exact:true}).click();await expect(page.locator('#opening-company option:checked')).toHaveText('Sintetik maktab 52');
 await page.locator('#filter-company').selectOption('');const balances=page.locator('section.panel').filter({has:page.getByRole('heading',{name:'Maktab avanslari va kreditlari',exact:true})});await balances.getByRole('button',{name:'Keyingi maktab qoldiqlari'}).click();await expect(balances.getByText('school-52',{exact:true})).toBeVisible();await expect(page.getByRole('region',{name:'Avans taqsimoti oqibatlari',exact:true})).toHaveCount(0);
});
