import {test,expect} from '@playwright/test';
test('owner session protects all school screens and can be revoked',async({page})=>{await page.goto('/schools');await expect(page.getByRole('heading',{name:'Barcha avtomaktablar nazorati'})).toBeVisible();await expect(page.getByRole('button',{name:'Sinov egasi sifatida kirish'})).toBeVisible();await page.getByRole('button',{name:'Sinov egasi sifatida kirish'}).click();await expect(page.getByRole('heading',{name:'Avtomaktablar',exact:true})).toBeVisible();await expect(page.getByText('Namunaviy ma’lumot · Sintetik',{exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:'Avtomaktablar',exact:true})).toBeVisible();await page.getByRole('button',{name:'Chiqish',exact:true}).first().click();await expect(page.getByRole('button',{name:'Sinov egasi sifatida kirish'})).toBeVisible();await page.goto('/invoices');await expect(page.getByRole('heading',{name:'Barcha avtomaktablar nazorati'})).toBeVisible();});
test('narrow menu preserves URL scope and supports back navigation',async({page})=>{await page.setViewportSize({width:360,height:800});await page.goto('/?from=2026-10-01&to=2026-11-01');await page.getByRole('button',{name:'Sinov egasi sifatida kirish'}).click();await expect(page.getByRole('heading',{name:'Umumiy ko‘rinish',exact:true})).toBeVisible();await page.getByRole('button',{name:'Bo‘limlar menyusini ochish'}).click();await page.getByRole('dialog').getByRole('link',{name:'Tashriflar',exact:true}).click();await expect(page).toHaveURL(/\/traffic\?.*from=2026-10-01/);await expect(page.getByRole('heading',{name:'Tashriflar',exact:true})).toBeVisible();await page.goBack();await expect(page.getByRole('heading',{name:'Umumiy ko‘rinish',exact:true})).toBeVisible();await expect(page.getByLabel('Boshlanish sanasi',{exact:true})).toHaveValue('2026-10-01');await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);});
test('production configuration never offers synthetic founder access',async({page})=>{await page.route('**/api/v1/auth/config',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({data:{environment:'production',providerConfigured:false},meta:{requestId:'synthetic-test-config',apiVersion:1}})}));await page.goto('/');await expect(page.getByText('Kirish provayderi sozlanmagan yoki hozir javob bermayapti.')).toBeVisible();await expect(page.getByRole('button',{name:'Sinov egasi sifatida kirish'})).toHaveCount(0);});
test('traffic pages and journey events remain visible alongside daily trends',async({page})=>{
 const meta={requestId:'synthetic-trend-test',apiVersion:1,status:'partial',warnings:['Kuzatuv qamrovi qisman']};const session={actorId:'synthetic-trend-owner',displayName:'Sintetik egasi',csrfToken:'synthetic-csrf',environment:'synthetic'};
 await page.route('**/api/v1/auth/session',route=>route.fulfill({json:{data:session,meta}}));await page.route('**/api/v1/commands?*',route=>route.fulfill({json:{data:{items:[]},meta}}));await page.route('**/api/v1/schools?*',route=>route.fulfill({json:{data:{items:[],nextCursor:null},meta}}));
 await page.route('**/api/v1/traffic/summary?*',route=>route.fulfill({json:{data:{metrics:[],series:[{date:'2026-10-01',value:2}],items:[{page:'/courses',count:'2'}]},meta}}));await page.route('**/api/v1/traffic/sources?*',route=>route.fulfill({json:{data:{items:[],nextCursor:null},meta}}));
 await page.route('**/api/v1/journeys?*',route=>route.fulfill({json:{data:{metrics:[{key:'events',label:'Davrda kuzatilgan hodisalar',value:'3',unit:'count'}],series:[{date:'2026-10-01',value:3},{date:'2026-10-02',value:null}],items:[{event:'usage.action',source:'crm',occurredAt:'2026-10-01T04:00:00Z'}],summary:'Ro‘yxatda oxirgi 100 ta hodisa bor; kuzatuvi yo‘q kunlar nol deb olinmaydi.'},meta}}));
 await page.goto('/traffic?from=2026-10-01&to=2026-10-03');await expect(page.getByRole('table',{name:'Trendning jadval ko‘rinishi'})).toBeVisible();await expect(page.getByRole('table',{name:'Eng ko‘p kuzatilgan 100 ta sahifa'}).getByText('/courses',{exact:true})).toBeVisible();await expect(page.getByText('Kuzatuv qamrovi qisman',{exact:true}).first()).toBeVisible();
 await page.goto('/journeys?from=2026-10-01&to=2026-10-03');await expect(page.getByRole('table',{name:'Tanlangan davrdagi oxirgi 100 ta hodisa'}).getByText('usage.action',{exact:true})).toBeVisible();await expect(page.getByRole('table',{name:'Trendning jadval ko‘rinishi'}).getByText('Ma’lumot yo‘q',{exact:true})).toBeVisible();await expect(page.locator('.metric-value')).toHaveText('3');
});
