import {test,expect} from '@playwright/test';
const meta={requestId:'scope-browser-test',apiVersion:1,status:'partial',dataThrough:'2026-10-01T00:00:00Z',warnings:['Ikkinchi manba hali kelmagan']};
test('unknown values stay explicit and old-scope response never replaces new filters',async({page})=>{
 await page.route('**/api/v1/schools?**',route=>route.fulfill({json:{data:{items:[{id:'school-a',name:'Sintetik A',status:'active',activeStudents:1,branchesCount:1},{id:'school-b',name:'Sintetik B',status:'active',activeStudents:2,branchesCount:1}]},meta}}));
 await page.route('**/api/v1/schools/school-**',route=>route.fulfill({json:{data:{id:'school-b',name:'Sintetik B',status:'active',branches:[]},meta}}));
 await page.route('**/api/v1/schools/school-*/branches?*',route=>route.fulfill({json:{data:{items:[],nextCursor:null},meta}}));
 await page.route('**/api/v1/overview?**',async route=>{const company=new URL(route.request().url()).searchParams.get('companyId');if(company==='school-a')await new Promise(resolve=>setTimeout(resolve,500));try{await route.fulfill({json:{data:{metrics:[{key:'schools',label:'Maktablar',value:company==='school-b'?'222':company==='school-a'?'111':null,unit:'count',definitionVersion:'test-v1'}],schools:[],attention:[]},meta}});}catch{/* superseded request is intentionally canceled */}});
 await page.goto('/');await page.getByRole('button',{name:'Sinov egasi sifatida kirish'}).click();await expect(page.locator('.metric-value')).toHaveText('Ma’lumot yo‘q');await expect(page.getByText('Ikkinchi manba hali kelmagan',{exact:true})).toBeVisible();await page.getByLabel('Avtomaktab',{exact:true}).selectOption('school-a');await page.getByLabel('Avtomaktab',{exact:true}).selectOption('school-b');await expect(page.locator('.metric-value')).toHaveText('222');await page.waitForTimeout(600);await expect(page.locator('.metric-value')).toHaveText('222');await page.reload();await expect(page.getByLabel('Avtomaktab',{exact:true})).toHaveValue('school-b');
});
test('session expiry removes protected content instead of retaining cached school values',async({page})=>{
 await page.goto('/schools');await page.getByRole('button',{name:'Sinov egasi sifatida kirish'}).click();await expect(page.getByRole('heading',{name:'Avtomaktablar',exact:true})).toBeVisible();await page.route('**/api/v1/schools?**',route=>route.fulfill({status:401,json:{error:{code:'SESSION_EXPIRED',message:'expired',retryable:false},meta:{requestId:'expired-test',apiVersion:1}}}));await page.getByRole('button',{name:'Ma’lumotlarni yangilash'}).click();await expect(page.getByRole('heading',{name:'Barcha avtomaktablar nazorati'})).toBeVisible();await expect(page.getByRole('heading',{name:'Avtomaktablar',exact:true})).toHaveCount(0);
});

test('global school pages and search retain later names while school changes and Back/Forward preserve branch ownership',async({page})=>{
 const session={actorId:'synthetic-scope-owner',displayName:'Sintetik egasi',csrfToken:'synthetic-csrf',environment:'synthetic'};const schools=Array.from({length:52},(_,index)=>({id:`school-${index+1}`,name:`Sintetik maktab ${index+1}`,status:'active',activeStudents:1,branchesCount:1}));
 await page.route('**/api/v1/auth/session',route=>route.fulfill({json:{data:session,meta}}));await page.route('**/api/v1/commands?*',route=>route.fulfill({json:{data:{items:[]},meta}}));
 await page.route('**/api/v1/schools?*',route=>{const query=new URL(route.request().url()).searchParams;expect(query.get('limit')).toBe('50');const items=schools.filter(school=>school.name.includes(query.get('search')??''));const offset=query.get('cursor')?50:0;return route.fulfill({json:{data:{items:items.slice(offset,offset+50),nextCursor:items.length>offset+50?'school-50':null},meta}});});
 await page.route('**/api/v1/schools/school-*?*',route=>{const id=new URL(route.request().url()).pathname.split('/').at(-1);const school=schools.find(item=>item.id===id)!;return route.fulfill({json:{data:{...school,branches:[{id:id!.replace('school-','branch-'),name:`Filial ${id}`,status:'active'}]},meta}});});
 await page.route('**/api/v1/schools/school-*/branches?*',route=>{const id=new URL(route.request().url()).pathname.split('/').at(-2)!;return route.fulfill({json:{data:{items:[{id:id.replace('school-','branch-'),name:`Filial ${id}`,status:'active'}],nextCursor:null},meta}});});
 await page.route('**/api/v1/overview?*',route=>route.fulfill({json:{data:{metrics:[],schools:[],attention:[]},meta}}));
 await page.goto('/?companyId=school-52&branchId=branch-52');await expect(page.locator('#filter-company option:checked')).toHaveText('Sintetik maktab 52');await expect(page.locator('#filter-branch')).toHaveValue('branch-52');const filters=page.getByRole('region',{name:'Davr va maktab filtrlari'});
 await filters.getByRole('button',{name:'Keyingi maktablar'}).click();await page.locator('#filter-company').selectOption('school-51');await expect(page.locator('#filter-branch')).toHaveValue('');await expect(page).toHaveURL(/companyId=school-51/);expect(new URL(page.url()).searchParams.has('branchId')).toBe(false);
 await filters.getByRole('button',{name:'Oldingi maktablar'}).click();await expect(page.locator('#filter-company option:checked')).toHaveText('Sintetik maktab 51');await page.locator('#filter-company-search').fill('maktab 52');await page.locator('#filter-company').selectOption('school-52');await page.locator('#filter-branch').selectOption('branch-52');await expect(page).toHaveURL(/branchId=branch-52/);
 await page.goBack();await expect(page.locator('#filter-company')).toHaveValue('school-52');await expect(page.locator('#filter-branch')).toHaveValue('');await page.goBack();await expect(page.locator('#filter-company option:checked')).toHaveText('Sintetik maktab 51');await expect(page.locator('#filter-branch')).toHaveValue('');
 await page.goForward();await expect(page.locator('#filter-company option:checked')).toHaveText('Sintetik maktab 52');await page.reload();await expect(page.locator('#filter-company option:checked')).toHaveText('Sintetik maktab 52');
});

test('global branch pages retain known selection and URL context without accepting an old school response',async({page})=>{
 const session={actorId:'synthetic-branch-owner',displayName:'Sintetik egasi',csrfToken:'synthetic-csrf',environment:'synthetic'};const schools=[{id:'school-a',name:'Sintetik A',status:'active',activeStudents:1,branchesCount:102},{id:'school-b',name:'Sintetik B',status:'active',activeStudents:1,branchesCount:1}];const branches=Array.from({length:102},(_,index)=>({id:`branch-a-${String(index+1).padStart(3,'0')}`,name:`Sintetik A filiali ${index+1}`,status:'active'}));const branchRequests:Array<{school:string;cursor:string}>=[];
 let refreshedRoster=false;let holdOldPage=false;let releaseOld=()=>{};let startOld=()=>{};let finishOld=()=>{};const oldStarted=new Promise<void>(resolve=>{startOld=resolve;});const oldFinished=new Promise<void>(resolve=>{finishOld=resolve;});
 await page.route('**/api/v1/auth/session',route=>route.fulfill({json:{data:session,meta}}));await page.route('**/api/v1/commands?*',route=>route.fulfill({json:{data:{items:[]},meta}}));
 await page.route('**/api/v1/schools?*',route=>route.fulfill({json:{data:{items:schools,nextCursor:null},meta}}));await page.route('**/api/v1/schools/school-*?*',route=>{const id=new URL(route.request().url()).pathname.split('/').at(-1);return route.fulfill({json:{data:{...schools.find(school=>school.id===id),branches:[]},meta}});});
 await page.route('**/api/v1/schools/school-*/branches?*',async route=>{
  const url=new URL(route.request().url()),school=url.pathname.split('/').at(-2)!,cursor=url.searchParams.get('cursor')??'';expect(url.searchParams.get('limit')).toBe('50');expect(url.searchParams.has('branchId')).toBe(false);branchRequests.push({school,cursor});const items=school==='school-a'?branches:Array.from({length:refreshedRoster?51:1},(_,index)=>({id:`branch-b-${String(index+1).padStart(3,'0')}`,name:`Sintetik B filiali ${index+1}`,status:'active'}));const offset=cursor?items.findIndex(branch=>branch.id===cursor)+1:0;const data={items:items.slice(offset,offset+50),nextCursor:items.length>offset+50?items[offset+49]!.id:null};
  if(holdOldPage&&school==='school-a'&&cursor==='branch-a-050'){holdOldPage=false;startOld();await new Promise<void>(resolve=>{releaseOld=resolve;});try{await route.fulfill({json:{data,meta}});}catch{/* superseded branch request is intentionally canceled */}finally{finishOld();}return;}
  await route.fulfill({json:{data,meta}});
 });
 await page.route('**/api/v1/overview?*',route=>route.fulfill({json:{data:{metrics:[],schools:[],attention:[]},meta}}));
 await page.goto('/');const filters=page.getByRole('region',{name:'Davr va maktab filtrlari'});const branch=page.locator('#filter-branch');await expect(branch).toBeDisabled();await expect(filters.getByRole('button',{name:'Keyingi filiallar'})).toHaveCount(0);expect(branchRequests).toHaveLength(0);
 await page.locator('#filter-company').selectOption('school-a');const next=filters.getByRole('button',{name:'Keyingi filiallar'});await expect(next).toBeEnabled();await next.focus();await next.press('Enter');await expect(branch.locator('option[value="branch-a-051"]')).toHaveText('Sintetik A filiali 51');await next.click();await expect(branch.locator('option[value="branch-a-102"]')).toHaveText('Sintetik A filiali 102');await branch.selectOption('branch-a-102');await expect(page).toHaveURL(/branchId=branch-a-102/);await expect(next).toBeDisabled();
 await filters.getByRole('button',{name:'Oldingi filiallar'}).click();await expect(branch).toHaveValue('branch-a-102');await expect(branch.locator('option:checked')).toHaveText('Sintetik A filiali 102');await filters.getByRole('button',{name:'Oldingi filiallar'}).click();await expect(branch.locator('option:checked')).toHaveText('Sintetik A filiali 102');
 await page.locator('#filter-company').selectOption('school-b');await expect(branch).toHaveValue('');expect(new URL(page.url()).searchParams.has('branchId')).toBe(false);await expect(filters.getByRole('button',{name:'Oldingi filiallar'})).toBeDisabled();await expect(branch.locator('option[value="branch-b-001"]')).toHaveText('Sintetik B filiali 1');await expect(page.getByText('Maktab o‘zgardi; filial filtri tozalandi.',{exact:true})).toBeVisible();
 await branch.selectOption('branch-b-001');await page.goBack();await expect(branch).toHaveValue('');await page.goBack();await expect(page.locator('#filter-company')).toHaveValue('school-a');await expect(branch).toHaveValue('branch-a-102');await page.goForward();await expect(page.locator('#filter-company')).toHaveValue('school-b');await expect(branch).toHaveValue('');await page.goForward();await expect(branch).toHaveValue('branch-b-001');await page.goBack();await page.goBack();await expect(branch).toHaveValue('branch-a-102');
 await page.reload();await expect(branch).toHaveValue('branch-a-102');await expect(branch.locator('option:checked')).toHaveText('Tanlangan filial nomi bu sahifada mavjud emas · branch-a-102');await expect(next).toBeEnabled();holdOldPage=true;await next.click();await oldStarted;await expect(branch).toHaveAttribute('aria-busy','true');await expect(filters.getByText('Filiallar olinmoqda…',{exact:true})).toBeVisible();await page.locator('#filter-company').selectOption('school-b');await expect(branch.locator('option[value="branch-b-001"]')).toHaveText('Sintetik B filiali 1');releaseOld();await oldFinished;await expect(branch).toHaveValue('');await expect(branch).toHaveAttribute('aria-busy','false');await expect(branch.locator('option[value^="branch-a-"]')).toHaveCount(0);await expect(filters.getByRole('button',{name:'Oldingi filiallar'})).toBeDisabled();expect(branchRequests.at(-1)).toEqual({school:'school-b',cursor:''});
 await expect(next).toBeDisabled();await expect(page.locator('#filter-company option[value="school-c"]')).toHaveCount(0);await expect(branch.locator('option[value="branch-b-002"]')).toHaveCount(0);schools[1]!.name='Yangilangan sintetik B';schools[1]!.branchesCount=51;schools.push({id:'school-c',name:'Yangi sintetik C',status:'active',activeStudents:1,branchesCount:1});refreshedRoster=true;
 await page.getByRole('button',{name:'Ma’lumotlarni yangilash',exact:true}).click();await expect(page.locator('#filter-company option:checked')).toHaveText('Yangilangan sintetik B');await expect(page.locator('#filter-company option[value="school-c"]')).toHaveText('Yangi sintetik C');await expect(branch.locator('option[value="branch-b-002"]')).toHaveText('Sintetik B filiali 2');await expect(branch).toHaveValue('');await expect(next).toBeEnabled();await next.click();await expect(branch.locator('option[value="branch-b-051"]')).toHaveText('Sintetik B filiali 51');await expect(next).toBeDisabled();expect(branchRequests.at(-1)).toEqual({school:'school-b',cursor:'branch-b-050'});
});
