import {afterAll,describe,expect,it} from 'vitest';
import {randomUUID} from 'node:crypto';
import {sql,type SQL} from 'drizzle-orm';
import {createDatabase} from '../src/db/index.js';
import {ProductStore,type ProductExecutor} from '../src/db/product-store.js';
import {loadConfig} from '../src/platform/config.js';
import {BillingService,type BillingBasisProvider} from '../src/modules/billing/billing.service.js';
import {CommandRegistry} from '../src/modules/commands/registry.js';

const database=createDatabase(loadConfig({APP_ENV:'synthetic',DATABASE_URL:process.env.DATABASE_URL}));
const actor={id:'billing-test-owner',environment:'synthetic' as const};
const basis:BillingBasisProvider=async()=>({complete:true,blockers:[],coverageFrom:'2026-01-01',dataThrough:'2026-10-08',checkpoint:'fixture-source-1',intervals:[]});
const service=new BillingService(new ProductStore(database),basis,()=>new Date('2026-10-08T12:00:00Z'));
afterAll(()=>database.pool.end());
const binding=(preview:{previewId:string;previewHash:string;ledgerRevision:string;input:Record<string,unknown>})=>({...preview.input,previewId:preview.previewId,expectedPreviewHash:preview.previewHash,expectedLedgerRevision:preview.ledgerRevision});
async function fixedInvoice(amountMinor='100000',effectiveFrom='2026-10-01'){
 const status=await service.policyStatus(actor),confirmed=await service.confirmPolicy(actor,{confirmed:true,expectedPolicyHash:status.policyHash},randomUUID());
 const companyId='money-'+randomUUID(),preview=await service.previewContract(actor,{action:'create',companyId,planType:'fixed_monthly',amountMinor,currency:'UZS',businessTimezone:'Asia/Tashkent',effectiveFrom,policyRevisionId:confirmed.revisionId});
 const contract=await service.createContract(actor,binding(preview),randomUUID()),activation=await service.previewContract(actor,{action:'confirm',contractId:contract.id,expectedRevision:contract.revision});
 await service.confirmContract(actor,contract.id,binding(activation),randomUUID());
 const invoicePreview=await service.previewInvoice(actor,contract.id,{periodStart:'2026-10-01',periodEnd:'2026-11-01'});
 return {companyId,contractId:contract.id,invoice:await service.closeInvoice(actor,contract.id,binding(invoicePreview),randomUUID())};
}

describe('reviewed platform billing',()=>{
 it('durably rejects a racing new key while retaining and recovering the original unknown intent',async()=>{
  const owner={...actor,id:'recovery-'+randomUUID()},registry=new CommandRegistry(new ProductStore(database),service),oldKey=randomUUID(),newKey=randomUUID(),path='/billing/policy-confirmations';
  const policy=await service.policyStatus(owner),body={confirmed:true,expectedPolicyHash:policy.policyHash};let rejectedWork=0;
  await registry.register(owner,oldKey,path,body);
  await expect(registry.run(owner,newKey,path,body,async()=>{rejectedWork++;return {};})).rejects.toMatchObject({code:'UNKNOWN_COMMAND',status:409});
  expect(rejectedWork).toBe(0);expect(await registry.status(owner,oldKey)).toEqual({state:'unknown'});
  expect(await registry.status(owner,newKey)).toMatchObject({state:'notCommitted',code:'UNKNOWN_COMMAND'});
  expect(await registry.status({...owner,id:'different-owner'},newKey)).toEqual({state:'unknown'});
  await registry.acknowledge(owner,newKey);
  expect((await registry.discover(owner)).items.map(item=>item.key)).toEqual([oldKey]);
  const recovered=await registry.run(owner,oldKey,path,body,()=>service.confirmPolicy(owner,body,oldKey));
  expect((await registry.status(owner,oldKey)).state).toBe('committed');
  expect((await registry.run(owner,oldKey,path,body,()=>service.confirmPolicy(owner,body,oldKey))).revisionId).toBe(recovered.revisionId);
  await registry.acknowledge(owner,oldKey);expect((await registry.discover(owner)).items).toEqual([]);
  await expect(registry.run(owner,newKey,path,body,async()=>{rejectedWork++;return {};})).rejects.toMatchObject({code:'UNKNOWN_COMMAND'});expect(rejectedWork).toBe(0);
 });
 it('creates a reviewed draft contract once and recovers the committed original intent',async()=>{
  const policy=await service.policyStatus(actor);
  const confirmed=await service.confirmPolicy(actor,{confirmed:true,expectedPolicyHash:policy.policyHash},randomUUID());
  const companyId='bill-'+randomUUID();
  const preview=await service.previewContract(actor,{action:'create',companyId,planType:'fixed_monthly',amountMinor:'31000',currency:'UZS',businessTimezone:'Asia/Tashkent',effectiveFrom:'2026-10-01',policyRevisionId:confirmed.revisionId});
  const key=randomUUID(),request=binding(preview);
  const first=await service.createContract(actor,request,key);
  expect(first.status).toBe('draft');
  const replay=await service.createContract(actor,request,key);
  expect(replay.id).toBe(first.id);
  expect(replay.replayed).toBe(true);
  const recovered=await service.commandStatus(actor,key);
  expect(recovered.state).toBe('committed');
  expect((recovered.result as {id:string}).id).toBe(first.id);
  expect(await service.commandStatus({...actor,id:'different-owner'},key)).toEqual({state:'unknown'});
 await expect(service.createContract(actor,{...request,amountMinor:'32000'},key)).rejects.toMatchObject({code:'IDEMPOTENCY_CONFLICT'});
 });
 it('closes an advance fixed invoice from the reviewed source and preserves original facts',async()=>{
  const policy=await service.policyStatus(actor),companyId='fixed-'+randomUUID();
  const draftPreview=await service.previewContract(actor,{action:'create',companyId,planType:'fixed_monthly',amountMinor:'31000',currency:'UZS',businessTimezone:'Asia/Tashkent',effectiveFrom:'2026-10-01',policyRevisionId:policy.revisionId});
  const draft=await service.createContract(actor,binding(draftPreview),randomUUID());
  const activationPreview=await service.previewContract(actor,{action:'confirm',contractId:draft.id,expectedRevision:draft.revision});
  await service.confirmContract(actor,draft.id,binding(activationPreview),randomUUID());
  const preview=await service.previewInvoice(actor,draft.id,{periodStart:'2026-10-01',periodEnd:'2026-11-01'});
  expect(preview.canClose).toBe(true);
  expect(preview.totalMinor).toBe('31000');
  const key=randomUUID(),request=binding(preview),invoice=await service.closeInvoice(actor,draft.id,request,key);
  expect(invoice.outstandingMinor).toBe('31000');
  expect(invoice.dueDate).toBe('2026-10-15');
  expect((await service.closeInvoice(actor,draft.id,request,key)).id).toBe(invoice.id);
  await expect(database.db.execute(sql`UPDATE billing_invoices SET total_minor=1 WHERE id=${invoice.id}`)).rejects.toThrow();
  expect((await service.getInvoice(actor,invoice.id)).totalMinor).toBe('31000');
 });
 it('suggests reviewed oldest-due allocations and keeps overpayment as school credit',async()=>{
  const {companyId,invoice}=await fixedInvoice();
  const input={companyId,amount:{currency:'UZS',minor:'60000'},receivedAt:'2026-10-08T11:00:00Z',method:'bank_transfer',reference:'synthetic receipt'};
  const firstPreview=await service.previewPayment(actor,input),first=await service.recordPayment(actor,binding(firstPreview),randomUUID());
  expect(first.allocatedMinor).toBe('60000');
  expect(first.unallocatedMinor).toBe('0');
  expect((await service.getInvoice(actor,invoice.id)).outstandingMinor).toBe('40000');
  const secondPreview=await service.previewPayment(actor,input),second=await service.recordPayment(actor,binding(secondPreview),randomUUID());
  expect(second.allocatedMinor).toBe('40000');
  expect(second.unallocatedMinor).toBe('20000');
  expect((await service.getInvoice(actor,invoice.id)).outstandingMinor).toBe('0');
 expect((await service.getPayment(actor,second.id)).amount.minor).toBe('60000');
 });
 it('rejects a stale reversal after allocation and then reverses the full receipt once',async()=>{
  const {companyId,invoice}=await fixedInvoice();
  const paymentPreview=await service.previewPayment(actor,{companyId,amount:{currency:'UZS',minor:'150000'},receivedAt:'2026-10-08T11:00:00Z',method:'cash',allocations:[]});
  const payment=await service.recordPayment(actor,binding(paymentPreview),randomUUID());
  const stale=await service.previewReversal(actor,payment.id,{reason:'Synthetic receipt correction'});
  const allocation=await service.previewAllocations(actor,payment.id,{allocations:[{invoiceId:invoice.id,amountMinor:'100000'}]});
  const allocated=await service.allocatePayment(actor,payment.id,binding(allocation),randomUUID());
  expect(allocated.unallocatedMinor).toBe('50000');
  const staleKey=randomUUID();
  await expect(service.reversePayment(actor,payment.id,binding(stale),staleKey)).rejects.toMatchObject({code:'REVERSAL_PREVIEW_STALE'});
  expect(await service.commandStatus(actor,staleKey)).toMatchObject({state:'notCommitted',code:'REVERSAL_PREVIEW_STALE'});
  expect((await service.getInvoice(actor,invoice.id)).outstandingMinor).toBe('0');
  const preview=await service.previewReversal(actor,payment.id,{reason:'Synthetic receipt correction'}),key=randomUUID(),request=binding(preview);
  const reversed=await service.reversePayment(actor,payment.id,request,key);
  expect(reversed.reversed).toBe(true);
  expect(reversed.unallocatedMinor).toBe('0');
  expect((await service.getInvoice(actor,invoice.id)).outstandingMinor).toBe('100000');
  expect((await service.reversePayment(actor,payment.id,request,key)).replayed).toBe(true);
  await expect(service.reversePayment(actor,payment.id,{...request,previewId:stale.previewId},key)).rejects.toMatchObject({code:'IDEMPOTENCY_CONFLICT'});
 });
 it('preserves a paid original invoice and releases credit after an explicit correction',async()=>{
  const {companyId,invoice}=await fixedInvoice();
  const paymentPreview=await service.previewPayment(actor,{companyId,amount:{currency:'UZS',minor:'100000'},receivedAt:'2026-10-08T11:00:00Z',method:'bank_transfer'});
  const payment=await service.recordPayment(actor,binding(paymentPreview),randomUUID());
  const preview=await service.previewCorrection(actor,invoice.id,{type:'credit',correctedTotalMinor:'80000',reason:'Synthetic invoice correction'});
  const key=randomUUID(),corrected=await service.correctInvoice(actor,invoice.id,binding(preview),key);
  expect(corrected.totalMinor).toBe('100000');
  expect(corrected.correctedTotalMinor).toBe('80000');
  expect(corrected.outstandingMinor).toBe('0');
  expect((await service.getPayment(actor,payment.id)).unallocatedMinor).toBe('20000');
  expect((await service.correctInvoice(actor,invoice.id,binding(preview),key)).id).toBe(invoice.id);
  const reversal=await service.previewReversal(actor,payment.id,{reason:'Synthetic wrong receipt'});
  await service.reversePayment(actor,payment.id,binding(reversal),randomUUID());
  expect((await service.getInvoice(actor,invoice.id)).outstandingMinor).toBe('80000');
 });
 it('records one reviewed historical opening debt without inventing student-day history',async()=>{
  const companyId='opening-'+randomUUID();
  const preview=await service.previewOpeningBalance(actor,{companyId,amount:{currency:'UZS',minor:'70000'},asOf:'2026-09-30',dueDate:'2026-09-25',reason:'Synthetic owner-confirmed opening debt'});
  const key=randomUUID(),invoice=await service.recordOpeningBalance(actor,binding(preview),key);
  expect(invoice.kind).toBe('opening');
  expect(invoice.contractId).toBe(null);
  expect(invoice.lines).toEqual([]);
  expect(invoice.outstandingMinor).toBe('70000');
  expect(invoice.dueDate).toBe('2026-09-25');
  expect((await service.recordOpeningBalance(actor,binding(preview),key)).id).toBe(invoice.id);
  const duplicate=await service.previewOpeningBalance(actor,{...preview.input,amount:{currency:'UZS',minor:'50000'}});
  expect(duplicate.canCommit).toBe(false);
  expect(duplicate.blockers).toContain('OPENING_BALANCE_ALREADY_RECORDED');
  const payment=await service.previewPayment(actor,{companyId,amount:{currency:'UZS',minor:'30000'},receivedAt:'2026-10-08T11:00:00Z',method:'bank_transfer'});
  await service.recordPayment(actor,binding(payment),randomUUID());
  expect((await service.getInvoice(actor,invoice.id)).outstandingMinor).toBe('40000');
 });
 it('keeps acknowledgment separate from payment and changes the notice after ledger changes',async()=>{
  const {companyId,invoice}=await fixedInvoice();
  const later=new BillingService(new ProductStore(database),basis,()=>new Date('2026-10-20T12:00:00Z'));
  const notices=await later.listReminders(actor,companyId),notice=notices[0]!;
  expect(notice.overdueDays).toBe(5);
  expect(notice.amountMinor).toBe('100000');
  expect((await later.listReminders(actor,companyId))[0]!.id).toBe(notice.id);
  const key=randomUUID();await later.acknowledgeReminder(actor,notice.id,{},key);
  expect((await later.listReminders(actor,companyId))[0]!.acknowledged).toBe(true);
  expect((await service.getInvoice(actor,invoice.id)).outstandingMinor).toBe('100000');
  const preview=await later.previewPayment(actor,{companyId,amount:{currency:'UZS',minor:'40000'},receivedAt:'2026-10-20T11:00:00Z',method:'cash'});
  await later.recordPayment(actor,binding(preview),randomUUID());
  const changed=(await later.listReminders(actor,companyId))[0]!;
  expect(changed.amountMinor).toBe('60000');
  expect(changed.id).not.toBe(notice.id);
  expect(changed.acknowledged).toBe(false);
  await expect(later.acknowledgeReminder(actor,notice.id,{},randomUUID())).rejects.toMatchObject({code:'REMINDER_STATE_CHANGED'});
 });
 it('schedules the next period rate and cancels unused fixed days with immutable credit',async()=>{
  const {companyId,contractId,invoice}=await fixedInvoice();
  const current=await service.getContract(actor,contractId);
  await expect(service.previewContract(actor,{action:'revise',contractId,expectedRevision:current.revision,amountMinor:'200000',effectiveFrom:'2026-10-15'})).rejects.toMatchObject({code:'RATE_EFFECTIVE_DATE_INVALID'});
  const revisionPreview=await service.previewContract(actor,{action:'revise',contractId,expectedRevision:current.revision,amountMinor:'200000',effectiveFrom:'2026-11-01'});
  const revised=await service.reviseContract(actor,contractId,binding(revisionPreview),randomUUID());
  expect(revised.amountMinor).toBe('100000');
  expect((await service.getInvoice(actor,invoice.id)).totalMinor).toBe('100000');
  const paymentPreview=await service.previewPayment(actor,{companyId,amount:{currency:'UZS',minor:'100000'},receivedAt:'2026-10-08T11:00:00Z',method:'bank_transfer'});
  const payment=await service.recordPayment(actor,binding(paymentPreview),randomUUID());
  const cancellation=await service.previewContract(actor,{action:'cancel',contractId,expectedRevision:revised.revision,cancelAt:'2026-10-16',reason:'Synthetic early cancellation'});
  const key=randomUUID(),cancelled=await service.cancelContract(actor,contractId,binding(cancellation),key);
  expect(cancelled.status).toBe('cancelled');
  expect(cancelled.effectiveTo).toBe('2026-10-16');
  const after=await service.getInvoice(actor,invoice.id);
  expect(after.totalMinor).toBe('100000');
  expect(after.correctedTotalMinor).toBe('48387');
  expect(after.outstandingMinor).toBe('0');
  expect((await service.getPayment(actor,payment.id)).unallocatedMinor).toBe('51613');
  expect((await service.cancelContract(actor,contractId,binding(cancellation),key)).replayed).toBe(true);
 });
 it('filters before pagination and reports school credit without branch receivables',async()=>{
  const {companyId,invoice}=await fixedInvoice();
  const preview=await service.previewPayment(actor,{companyId,amount:{currency:'UZS',minor:'150000'},receivedAt:'2026-09-30T23:30:00Z',method:'cash'});
  await service.recordPayment(actor,binding(preview),randomUUID());
  expect(await service.listInvoices(actor,companyId,{from:'2026-09-01',to:'2026-10-01',timezone:'Asia/Tashkent'})).toEqual([]);
  expect((await service.listInvoices(actor,companyId,{from:'2026-10-01',to:'2026-11-01'}))[0]!.id).toBe(invoice.id);
  expect((await service.listPayments(actor,companyId,{from:'2026-10-01',to:'2026-11-01',timezone:'Asia/Tashkent'})).length).toBe(1);
  expect(await service.listPayments(actor,companyId,{from:'2026-10-01',to:'2026-11-01',timezone:'UTC'})).toEqual([]);
  expect((await service.listCredits(actor,companyId))[0]!.unallocatedMinor).toBe('50000');
  await expect(service.listInvoices(actor,companyId,{branchId:'fixture-branch'})).rejects.toMatchObject({code:'FINANCIAL_SCHOOL_SCOPE_ONLY'});
  const first=await service.listInvoicesPage(actor,undefined,{limit:1});
  expect(first.items.length).toBe(1);
  expect(first.nextCursor).not.toBe(null);
  const second=await service.listInvoicesPage(actor,undefined,{limit:1,cursor:first.nextCursor!});
  expect(second.items[0]!.id).not.toBe(first.items[0]!.id);
 });
 it('records known-school cash during source gaps while keeping new invoice calculation blocked',async()=>{
  const {companyId,contractId}=await fixedInvoice();
  await database.db.execute(sql`INSERT INTO analytics_schools(id,environment,name,slug,status,is_demo,deleted_at,data_through) VALUES(${companyId},'synthetic','Synthetic archived school',${companyId},'archived',false,'2026-10-01T00:00:00Z','2026-09-01T00:00:00Z')`);
  const incomplete:BillingBasisProvider=async()=>({complete:false,blockers:['SOURCE_GAP'],coverageFrom:null,dataThrough:null,checkpoint:'gap',intervals:[]});
  const gaps=new BillingService(new ProductStore(database),incomplete,()=>new Date('2026-10-08T12:00:00Z'),async(tx,id,environment)=>{const rows=await new ProductStore(database).query(tx,sql`SELECT id FROM analytics_schools WHERE id=${id} AND environment=${environment} AND is_demo=false`);return rows.length===1;});
  const preview=await gaps.previewPayment(actor,{companyId,amount:{currency:'UZS',minor:'100000'},receivedAt:'2026-10-08T11:00:00Z',method:'cash'});
  expect((await gaps.recordPayment(actor,binding(preview),randomUUID())).allocatedMinor).toBe('100000');
  const invoice=await gaps.previewInvoice(actor,contractId,{periodStart:'2026-11-01',periodEnd:'2026-12-01'});
  expect(invoice.canClose).toBe(false);
  expect(invoice.totalMinor).toBe(null);
  expect(invoice.blockers).toContain('SOURCE_NOT_READY');
  await expect(gaps.previewPayment(actor,{companyId:'unknown-'+randomUUID(),amount:{currency:'UZS',minor:'1'},receivedAt:'2026-10-08T11:00:00Z',method:'cash'})).rejects.toMatchObject({code:'SCHOOL_NOT_FOUND'});
 });
 it('serializes concurrent closes and recovers the same committed result',async()=>{
  const {companyId,contractId}=await fixedInvoice();
  const later=new BillingService(new ProductStore(database),basis,()=>new Date('2026-11-08T12:00:00Z'));
  const preview=await later.previewInvoice(actor,contractId,{periodStart:'2026-11-01',periodEnd:'2026-12-01'}),request=binding(preview),key=randomUUID();
  const [first,replay]=await Promise.all([later.closeInvoice(actor,contractId,request,key),later.closeInvoice(actor,contractId,request,key)]);
  expect(first.id).toBe(replay.id);
  expect([first.replayed,replay.replayed].filter(Boolean)).toHaveLength(1);
  expect(await later.listInvoices(actor,companyId,{from:'2026-11-01',to:'2026-12-01'})).toHaveLength(1);
  const december=new BillingService(new ProductStore(database),basis,()=>new Date('2026-12-08T12:00:00Z'));
  const left=await december.previewInvoice(actor,contractId,{periodStart:'2026-12-01',periodEnd:'2027-01-01'}),right=await december.previewInvoice(actor,contractId,{periodStart:'2026-12-01',periodEnd:'2027-01-01'});
  const results=await Promise.allSettled([december.closeInvoice(actor,contractId,binding(left),randomUUID()),december.closeInvoice(actor,contractId,binding(right),randomUUID())]);
  expect(results.filter(result=>result.status==='fulfilled')).toHaveLength(1);
  expect(results.filter(result=>result.status==='rejected')).toHaveLength(1);
  expect(await december.listInvoices(actor,companyId,{from:'2026-12-01',to:'2027-01-01'})).toHaveLength(1);
 });
 it('rolls back an unexpected failure and leaves the original intent safely unknown',async()=>{
  const {companyId,contractId}=await fixedInvoice();let fail=false;
  class FaultStore extends ProductStore {
   override async query<T extends Record<string,unknown>>(executor:ProductExecutor,query:SQL):Promise<T[]>{const rows=await super.query<T>(executor,query);if(fail&&rows.some(row=>row.contract_id===contractId&&row.period_start==='2026-11-01')){fail=false;throw new Error('SYNTHETIC_CONNECTION_DROP');}return rows;}
  }
  const failing=new BillingService(new FaultStore(database),basis,()=>new Date('2026-11-08T12:00:00Z'));
  const preview=await failing.previewInvoice(actor,contractId,{periodStart:'2026-11-01',periodEnd:'2026-12-01'}),request=binding(preview),key=randomUUID();fail=true;
  await expect(failing.closeInvoice(actor,contractId,request,key)).rejects.toThrow('SYNTHETIC_CONNECTION_DROP');
  expect(await failing.commandStatus(actor,key)).toEqual({state:'unknown'});
  expect(await failing.listInvoices(actor,companyId,{from:'2026-11-01',to:'2026-12-01'})).toEqual([]);
  const recovered=await failing.closeInvoice(actor,contractId,request,key);
  expect(recovered.outstandingMinor).toBe('100000');
  expect(await failing.commandStatus(actor,key)).toMatchObject({state:'committed'});
 });
 it('keeps a rejected command tombstone even if its old preview would become usable again',async()=>{
  const {companyId}=await fixedInvoice();let now=new Date('2026-10-08T12:00:00Z');
  const changing=new BillingService(new ProductStore(database),basis,()=>now),preview=await changing.previewPayment(actor,{companyId,amount:{currency:'UZS',minor:'1'},receivedAt:'2026-10-08T11:00:00Z',method:'cash'}),request=binding(preview),key=randomUUID();
  now=new Date('2026-10-08T12:16:00Z');
  await expect(changing.recordPayment(actor,request,key)).rejects.toMatchObject({code:'PREVIEW_STALE'});
  expect(await changing.commandStatus(actor,key)).toMatchObject({state:'notCommitted'});
  now=new Date('2026-10-08T12:00:00Z');
  await expect(changing.recordPayment(actor,request,key)).rejects.toMatchObject({code:'PREVIEW_STALE'});
  expect(await changing.listPayments(actor,companyId)).toEqual([]);
  const fresh=await changing.previewPayment(actor,{companyId,amount:{currency:'UZS',minor:'1'},receivedAt:'2026-10-08T11:00:00Z',method:'cash'});
  await expect(changing.recordPayment(actor,binding(fresh),key)).rejects.toMatchObject({code:'IDEMPOTENCY_CONFLICT'});
  expect((await changing.recordPayment(actor,binding(fresh),randomUUID())).allocatedMinor).toBe('1');
 });
 it('pages immutable preview basis and blocks a changed or incomplete active-student source',async()=>{
  const companyId='active-'+randomUUID();let count=102,complete=true;
  const activeBasis:BillingBasisProvider=async(_tx,_company,_from,_to,_environment,purpose)=>({complete:purpose==='fixed'||complete,blockers:complete?[]:['SOURCE_GAP'],coverageFrom:'2026-09-01',dataThrough:'2026-10-01',checkpoint:'fixture-'+count+'-'+complete,intervals:Array.from({length:count},(_,index)=>({subjectId:'synthetic-'+index,branchId:'fixture-branch',from:'2026-09-01',to:'2026-10-01',status:'active'}))});
  const active=new BillingService(new ProductStore(database),activeBasis,()=>new Date('2026-10-08T12:00:00Z'));
  const policy=await active.policyStatus(actor),draftPreview=await active.previewContract(actor,{action:'create',companyId,planType:'active_student',amountMinor:'30000',currency:'UZS',businessTimezone:'Asia/Tashkent',effectiveFrom:'2026-09-01',policyRevisionId:policy.revisionId});
  const draft=await active.createContract(actor,binding(draftPreview),randomUUID()),activation=await active.previewContract(actor,{action:'confirm',contractId:draft.id,expectedRevision:draft.revision});await active.confirmContract(actor,draft.id,binding(activation),randomUUID());
  const preview=await active.previewInvoice(actor,draft.id,{periodStart:'2026-09-01',periodEnd:'2026-10-01'});
  expect(preview.totalMinor).toBe('3060000');
  expect((preview.lines as unknown[])).toHaveLength(100);
  expect(preview.lineCount).toBe(102);
  const tail=await active.getInvoicePreviewLines(actor,preview.previewId,{cursor:'100',limit:100});expect(tail.items).toHaveLength(2);expect(tail.nextCursor).toBe(null);
  await expect(active.getInvoicePreviewLines({...actor,id:'other-owner'},preview.previewId)).rejects.toMatchObject({code:'NOT_FOUND'});
  count=100;
  await expect(active.closeInvoice(actor,draft.id,binding(preview),randomUUID())).rejects.toMatchObject({code:'PREVIEW_STALE'});
  complete=false;const blocked=await active.previewInvoice(actor,draft.id,{periodStart:'2026-09-01',periodEnd:'2026-10-01'});expect(blocked.totalMinor).toBe(null);expect(blocked.canClose).toBe(false);
  await expect(active.closeInvoice(actor,draft.id,binding(blocked),randomUUID())).rejects.toMatchObject({code:'SOURCE_NOT_READY'});
  complete=true;const fresh=await active.previewInvoice(actor,draft.id,{periodStart:'2026-09-01',periodEnd:'2026-10-01'}),invoice=await active.closeInvoice(actor,draft.id,binding(fresh),randomUUID());
  expect(invoice.totalMinor).toBe('3000000');
  expect((await active.getInvoiceLines(actor,invoice.id,{cursor:'98',limit:100})).items).toHaveLength(2);
  expect((await active.getInvoicePreviewLines(actor,preview.previewId,{cursor:'100'})).items).toHaveLength(2);
 });
 it('rejects a nonexistent calendar receipt date rather than normalizing it to another day',async()=>{
  const {companyId}=await fixedInvoice();
  await expect(service.previewPayment(actor,{companyId,amount:{currency:'UZS',minor:'1'},receivedAt:'2026-02-31T12:00:00Z',method:'cash'})).rejects.toMatchObject({code:'INVALID_REQUEST',status:400});
 });
 it('blocks an active-school total exceeding persisted monetary precision before posting',async()=>{
  const companyId='overflow-'+randomUUID(),largeBasis:BillingBasisProvider=async()=>({complete:true,blockers:[],coverageFrom:'2026-09-01',dataThrough:'2026-10-01',checkpoint:'precision-fixture',intervals:['subject-a','subject-b'].map(subjectId=>({subjectId,branchId:'fixture',from:'2026-09-01',to:'2026-10-01',status:'active'}))});
  const large=new BillingService(new ProductStore(database),largeBasis,()=>new Date('2026-10-08T12:00:00Z')),policy=await large.policyStatus(actor),draftPreview=await large.previewContract(actor,{action:'create',companyId,planType:'active_student',amountMinor:'999999999999999999999999999999',currency:'UZS',businessTimezone:'Asia/Tashkent',effectiveFrom:'2026-09-01',policyRevisionId:policy.revisionId});
  const draft=await large.createContract(actor,binding(draftPreview),randomUUID()),activation=await large.previewContract(actor,{action:'confirm',contractId:draft.id,expectedRevision:draft.revision});await large.confirmContract(actor,draft.id,binding(activation),randomUUID());
  const preview=await large.previewInvoice(actor,draft.id,{periodStart:'2026-09-01',periodEnd:'2026-10-01'});expect(preview.canClose).toBe(false);expect(preview.blockers).toContain('BILLING_AMOUNT_OVERFLOW');
  const key=randomUUID();await expect(large.closeInvoice(actor,draft.id,binding(preview),key)).rejects.toMatchObject({code:'BILLING_AMOUNT_OVERFLOW'});expect(await large.commandStatus(actor,key)).toMatchObject({state:'notCommitted'});
 });
 it('never posts a blocked automatic allocation preview as if it were a manual selection',async()=>{
  const {companyId,contractId}=await fixedInvoice('1','2018-01-01');
  const historical=Array.from({length:100},(_,index)=>{const start=new Date(Date.UTC(2018,index,1)).toISOString().slice(0,10),end=new Date(Date.UTC(2018,index+1,1)).toISOString().slice(0,10);return sql`(${randomUUID()},${actor.environment},${companyId},${contractId},${start},${end},1,'2026-10-15','2026-10-08T12:00:00Z',${JSON.stringify({currency:'UZS',lines:[],sourceCheckpoint:'synthetic-immutable-original'})}::jsonb)`;});
  await database.db.execute(sql`INSERT INTO billing_invoices(id,environment,company_id,contract_id,period_start,period_end,total_minor,due_date,closed_at,snapshot) VALUES ${sql.join(historical,sql`,`)}`);
  const input={companyId,amount:{currency:'UZS',minor:'101'},receivedAt:'2026-10-08T11:00:00Z',method:'cash'},preview=await service.previewPayment(actor,input);
  expect(preview.canCommit).toBe(false);expect(preview.blockers).toEqual(['ALLOCATION_LIMIT_REACHED']);expect((preview.input.allocations as unknown[])).toHaveLength(100);
  expect(JSON.stringify(preview)).not.toContain('_reviewEligibility');expect(JSON.stringify(preview)).not.toContain('_allocationMode');
  const key=randomUUID(),request=binding(preview),before=await new ProductStore(database).query(database.db,sql`SELECT revision::text FROM billing_company_ledgers WHERE environment=${actor.environment} AND company_id=${companyId}`);
  await expect(service.recordPayment(actor,request,key)).rejects.toMatchObject({code:'ALLOCATION_LIMIT_REACHED'});
  expect(await service.commandStatus(actor,key)).toMatchObject({state:'notCommitted',code:'ALLOCATION_LIMIT_REACHED'});
  await expect(service.recordPayment(actor,request,key)).rejects.toMatchObject({code:'ALLOCATION_LIMIT_REACHED'});
  expect(await service.listPayments(actor,companyId)).toEqual([]);
  const allocations=await new ProductStore(database).query(database.db,sql`SELECT count(*)::text AS count FROM billing_allocations WHERE environment=${actor.environment} AND company_id=${companyId}`);expect(allocations[0]!.count).toBe('0');
  const after=await new ProductStore(database).query(database.db,sql`SELECT revision::text FROM billing_company_ledgers WHERE environment=${actor.environment} AND company_id=${companyId}`);expect(after).toEqual(before);
  const manual=await service.previewPayment(actor,{...input,allocations:preview.input.allocations});expect(manual.canCommit).toBe(true);
  const posted=await service.recordPayment(actor,binding(manual),randomUUID());expect(posted.allocatedMinor).toBe('100');expect(posted.unallocatedMinor).toBe('1');
  await expect(service.recordPayment(actor,request,key)).rejects.toMatchObject({code:'ALLOCATION_LIMIT_REACHED'});
 });
 it('preserves the entire cancellation entitlement after an independent correction and receipt reversal',async()=>{
  const {companyId,contractId,invoice}=await fixedInvoice();
  const correction=await service.previewCorrection(actor,invoice.id,{type:'adjustment',correctedTotalMinor:'20000',reason:'Synthetic independent correction'});await service.correctInvoice(actor,invoice.id,binding(correction),randomUUID());
  const receipt=await service.previewPayment(actor,{companyId,amount:{currency:'UZS',minor:'20000'},receivedAt:'2026-10-08T11:00:00Z',method:'cash'}),payment=await service.recordPayment(actor,binding(receipt),randomUUID());
  const contract=await service.getContract(actor,contractId),preview=await service.previewContract(actor,{action:'cancel',contractId,expectedRevision:contract.revision,cancelAt:'2026-10-16',reason:'Synthetic independent cancellation'}),key=randomUUID();
  const result=await service.cancelContract(actor,contractId,binding(preview),key);
  expect(result.creditDeltaMinor).toBe('51613');
  expect((await service.getInvoice(actor,invoice.id)).correctedTotalMinor).toBe('0');
  expect((await service.getInvoice(actor,invoice.id)).totalMinor).toBe('100000');
  expect((await service.listCredits(actor,companyId))[0]!.unallocatedMinor).toBe('51613');
  expect((await service.getPayment(actor,payment.id)).unallocatedMinor).toBe('20000');
  expect((await service.cancelContract(actor,contractId,binding(preview),key)).replayed).toBe(true);
  const reversal=await service.previewReversal(actor,payment.id,{reason:'Synthetic receipt reversal after cancellation'});await service.reversePayment(actor,payment.id,binding(reversal),randomUUID());
  expect((await service.listCredits(actor,companyId))[0]!.unallocatedMinor).toBe('31613');
  expect((await service.getInvoice(actor,invoice.id)).outstandingMinor).toBe('0');
  expect(await service.listPayments(actor,companyId)).toHaveLength(1);
  const grants=await service.listSchoolCreditsPage(actor,companyId);expect(grants.items).toHaveLength(1);const grant=grants.items[0]!;
  expect(grant.amountMinor).toBe('31613');expect(grant.unallocatedMinor).toBe('31613');
  const charge=await service.previewCorrection(actor,invoice.id,{type:'adjustment',correctedTotalMinor:'10000',reason:'Synthetic independent new adjustment'});await service.correctInvoice(actor,invoice.id,binding(charge),randomUUID());
  const allocation=await service.previewSchoolCreditAllocation(actor,grant.id,{allocations:[{invoiceId:invoice.id,amountMinor:'10000'}]}),allocationKey=randomUUID();await service.allocateSchoolCredit(actor,grant.id,binding(allocation),allocationKey);
  expect((await service.getInvoice(actor,invoice.id)).outstandingMinor).toBe('0');expect((await service.getSchoolCredit(actor,grant.id)).unallocatedMinor).toBe('21613');
  expect((await service.allocateSchoolCredit(actor,grant.id,binding(allocation),allocationKey)).replayed).toBe(true);
  const voided=await service.previewCorrection(actor,invoice.id,{type:'void',reason:'Synthetic void after grant allocation'});await service.correctInvoice(actor,invoice.id,binding(voided),randomUUID());
  expect((await service.getSchoolCredit(actor,grant.id)).unallocatedMinor).toBe('31613');
  expect((await service.listCredits(actor,companyId))[0]).toMatchObject({receiptCreditMinor:'0',nonCashCreditMinor:'31613',unallocatedMinor:'31613'});
  await expect(database.db.execute(sql`UPDATE billing_school_credit_entries SET amount_minor=1 WHERE id=${grant.id}`)).rejects.toThrow();
  const chargeAgain=await service.previewCorrection(actor,invoice.id,{type:'adjustment',correctedTotalMinor:'30000',reason:'Synthetic mixed settlement'});await service.correctInvoice(actor,invoice.id,binding(chargeAgain),randomUUID());
  const newReceipt=await service.previewPayment(actor,{companyId,amount:{currency:'UZS',minor:'10000'},receivedAt:'2026-10-08T11:00:00Z',method:'cash'}),newPayment=await service.recordPayment(actor,binding(newReceipt),randomUUID());
  const newerGrant=await service.previewSchoolCreditAllocation(actor,grant.id,{allocations:[{invoiceId:invoice.id,amountMinor:'20000'}]});await service.allocateSchoolCredit(actor,grant.id,binding(newerGrant),randomUUID());
  const partial=await service.previewCorrection(actor,invoice.id,{type:'adjustment',correctedTotalMinor:'15000',reason:'Synthetic mixed partial correction'});
  expect(partial.releasedAllocations).toEqual([]);expect(partial.releasedCreditAllocations).toEqual([{creditId:grant.id,invoiceId:invoice.id,amountMinor:'15000'}]);await service.correctInvoice(actor,invoice.id,binding(partial),randomUUID());
  expect((await service.getPayment(actor,newPayment.id)).allocatedMinor).toBe('10000');expect((await service.getSchoolCredit(actor,grant.id)).unallocatedMinor).toBe('26613');
  const newReversal=await service.previewReversal(actor,newPayment.id,{reason:'Synthetic mixed receipt reversal'});await service.reversePayment(actor,newPayment.id,binding(newReversal),randomUUID());
  expect((await service.getInvoice(actor,invoice.id)).outstandingMinor).toBe('10000');expect((await service.getInvoice(actor,invoice.id)).creditAllocatedMinor).toBe('5000');
  const other=await fixedInvoice();await expect(service.previewSchoolCreditAllocation(actor,grant.id,{allocations:[{invoiceId:other.invoice.id,amountMinor:'1'}]})).rejects.toMatchObject({code:'ALLOCATION_CONFLICT'});
  await expect(service.getSchoolCredit({...actor,environment:'production'},grant.id)).rejects.toMatchObject({code:'NOT_FOUND'});
 });
 it('retains cancellation entitlement when an independent void already reduced the receivable to zero',async()=>{
  const {companyId,contractId,invoice}=await fixedInvoice(),voided=await service.previewCorrection(actor,invoice.id,{type:'void',reason:'Synthetic prior independent void'});await service.correctInvoice(actor,invoice.id,binding(voided),randomUUID());
  const contract=await service.getContract(actor,contractId),preview=await service.previewContract(actor,{action:'cancel',contractId,expectedRevision:contract.revision,cancelAt:'2026-10-16',reason:'Synthetic later cancellation'}),result=await service.cancelContract(actor,contractId,binding(preview),randomUUID());
  expect(result.creditDeltaMinor).toBe('51613');expect((await service.getInvoice(actor,invoice.id)).correctedTotalMinor).toBe('0');
  expect((await service.listCredits(actor,companyId))[0]).toMatchObject({receiptCreditMinor:'0',nonCashCreditMinor:'51613',unallocatedMinor:'51613'});expect(await service.listPayments(actor,companyId)).toEqual([]);
 });
});
