import {afterAll,expect,test} from 'vitest';
import {randomUUID} from 'node:crypto';
import type {EventEnvelope,QueryScope,SourceRecord} from '@automaktab/contracts';
import {createFoundationApplication,createCollectionRuntime} from '../src/application/index.js';
import {ProductStore} from '../src/db/product-store.js';
import {snapshotHash} from '../src/modules/schools/schools.service.js';
import {ReportingService} from '../src/modules/reporting/reporting.service.js';
const app=createFoundationApplication({APP_ENV:'synthetic',DATABASE_URL:process.env.DATABASE_URL});
afterAll(()=>app.close());
test('official learning, observed CRM usage and verified acquisition use trusted facts and exact surface scope',async()=>{
 const source='crm-'+randomUUID(),company=randomUUID(),branch=randomUUID(),subject=randomUUID(),now=new Date(),at=new Date(now.getTime()-60000).toISOString(),cutover=new Date(now.getTime()-2*86400000).toISOString(),token='synthetic-reporting-source';
 const runtime=createCollectionRuntime(app.database,{environment:'synthetic',trustedSource:source,trustedToken:token});
 const records:SourceRecord[]=[{aggregate_type:'company',aggregate_id:company,aggregate_version:'0',company_id:company,properties:{name:'Synthetic Reporting School',slug:'school-'+company,status:'active',is_demo:false,deleted_at:null}},{aggregate_type:'branch',aggregate_id:branch,aggregate_version:'0',company_id:company,properties:{company_id:company,name:'Synthetic Reporting Branch',is_active:true,deleted_at:null}},{aggregate_type:'student',aggregate_id:subject,aggregate_version:'0',company_id:company,properties:{company_id:company,branch_id:branch,status:'active',deleted_at:null}}];
 const snapshot={schema_version:1,source,environment:'synthetic',cutover_at:cutover,as_of:now.toISOString(),barrier_version:'0',records,heads:records.map(({aggregate_type,aggregate_id,aggregate_version})=>({aggregate_type,aggregate_id,aggregate_version})),signal_heads:[],snapshot_hash:snapshotHash(records),baseline_records:records,baseline_hash:snapshotHash(records)};
 await runtime.schools.acceptSnapshot(snapshot,'Bearer '+token);
 const base={schema_version:1 as const,source,environment:'synthetic' as const,occurred_at:at,effective_at:at,aggregate_version:'1'};
 const lead=randomUUID();const events:EventEnvelope[]=[{...base,event_id:randomUUID(),name:'learning.result',aggregate_type:'learning',aggregate_id:randomUUID(),company_id:company,properties:{branch_id:branch,subject_id:subject,outcome:'passed',practice:false,score:null}},{...base,event_id:randomUUID(),name:'learning.result',aggregate_type:'learning',aggregate_id:randomUUID(),company_id:company,properties:{branch_id:branch,subject_id:subject,outcome:'failed',practice:true,score:40}},{...base,event_id:randomUUID(),name:'usage.action',aggregate_type:'usage',aggregate_id:randomUUID(),company_id:company,properties:{action:'lesson.create',actor_id:'synthetic-teacher',role:'teacher',branch_id:branch}},{...base,event_id:randomUUID(),name:'lead.created',aggregate_type:'lead',aggregate_id:lead,properties:{lead_id:lead}},{...base,event_id:randomUUID(),name:'lead.school_linked',aggregate_type:'lead',aggregate_id:lead,aggregate_version:'2',company_id:company,properties:{lead_id:lead,company_id:company}}];
 expect((await runtime.collector.admit({events},'trusted','Bearer '+token)).accepted_event_ids).toHaveLength(5);await runtime.processBatch();
 const replays=events.filter(event=>['learning.result','usage.action','lead.created'].includes(event.name)).map(event=>({...event,event_id:randomUUID()}));
 expect((await runtime.collector.admit({events:replays},'trusted','Bearer '+token)).accepted_event_ids).toHaveLength(4);
 expect(await runtime.processBatch()).toMatchObject({applied:4,quarantined:0});
 const report=new ReportingService(new ProductStore(app.database),(actor,scope)=>runtime.schools.qualitySummary(actor,scope),source),actor={id:'synthetic-founder',environment:'synthetic' as const};
 const day=new Date(Date.parse(at)+5*3600000).toISOString().slice(0,10),next=new Date(Date.parse(day+'T00:00:00Z')+86400000).toISOString().slice(0,10),scope:QueryScope={from:day,to:next,timezone:'Asia/Tashkent',environment:'synthetic',companyId:company,branchId:branch};
 expect((await report.learning(actor,{...scope,surface:'learning'})).metrics.find(metric=>metric.key==='attempts')?.value).toBeNull();
 const signals=new Map<string,Record<string,unknown>>();for(const event of events)signals.set(event.aggregate_type+':'+event.aggregate_id,{aggregate_type:event.aggregate_type,aggregate_id:event.aggregate_id,aggregate_version:event.aggregate_version});
 await runtime.schools.acceptSnapshot({...snapshot,barrier_version:'5',as_of:new Date().toISOString(),signal_heads:[...signals.values()]},'Bearer '+token);
 expect((await report.learning(actor,{...scope,surface:'learning'})).metrics.find(metric=>metric.key==='attempts')?.value).toBe('1');
 expect((await report.learning(actor,{...scope,surface:'practice'})).metrics.find(metric=>metric.key==='passed')?.value).toBe('0');
 expect((await report.usage(actor,{...scope,surface:'tenant'})).metrics.find(metric=>metric.key==='actions')?.value).toBe('1');
 expect((await report.usage(actor,{...scope,surface:'marketing'})).metrics.find(metric=>metric.key==='actions')?.value).toBe('0');
 const journeys=await report.journeys(actor,{...scope,surface:undefined});
 expect(journeys.metrics.find(metric=>metric.key==='events')?.value).toBe('3');expect(journeys.series).toEqual([{date:day,value:3}]);expect(journeys.items).toHaveLength(3);
 const emptyDay=await report.journeys(actor,{...scope,from:next,to:new Date(Date.parse(next+'T00:00:00Z')+86400000).toISOString().slice(0,10),surface:undefined});
 expect(emptyDay.series).toEqual([{date:next,value:null}]);
 expect((await report.acquisition(actor,{...scope,branchId:undefined,surface:undefined})).metrics.map(metric=>metric.value)).toEqual(['1','1']);
 expect((await report.acquisition(actor,{...scope,companyId:randomUUID(),branchId:undefined,surface:undefined})).metrics.map(metric=>metric.value)).toEqual(['0','0']);
 expect((await report.acquisition(actor,{...scope,branchId:undefined,surface:'practice'})).metrics.map(metric=>metric.value)).toEqual(['0','0']);
 const branchAcquisition=await report.acquisition(actor,{...scope,surface:'marketing'});
 expect(branchAcquisition.metrics.map(metric=>metric.value)).toEqual([null,null]);
 expect(branchAcquisition.steps?.map(step=>step.count)).toEqual([null,null]);
 expect(branchAcquisition.summary).toContain('filial');
 expect((await report.learning(actor,{...scope,from:new Date(now.getTime()-10*86400000).toISOString().slice(0,10)})).metrics.find(metric=>metric.key==='attempts')?.value).toBeNull();
 const old=await report.reviseFunnel(actor,{name:'Synthetic ordered acquisition',steps:[{event:'lead.created',name:'Murojaat'},{event:'lead.school_linked',name:'Maktab'}],windowDays:7},randomUUID());
 const nextDefinition=await report.reviseFunnel(actor,{name:'Synthetic revised acquisition',steps:[{event:'lead.created',name:'Murojaat'},{event:'lead.school_linked',name:'Maktab'}],windowDays:8,expectedVersion:1},randomUUID(),String(old.id));expect(nextDefinition.version).toBe(2);
 await expect(report.reviseFunnel(actor,{name:'Stale edit',steps:[{event:'lead.created',name:'Murojaat'},{event:'lead.school_linked',name:'Maktab'}],windowDays:8,expectedVersion:1},randomUUID(),String(old.id))).rejects.toMatchObject({code:'DEFINITION_STALE'});
 const usage=events.find(event=>event.name==='usage.action')!;
 await runtime.collector.admit({events:[{...usage,event_id:randomUUID(),properties:{...usage.properties,action:'student.create'}}]},'trusted','Bearer '+token);
 expect(await runtime.processBatch()).toMatchObject({applied:0,quarantined:1});
 expect((await report.learning(actor,{...scope,surface:'learning'})).metrics.find(metric=>metric.key==='attempts')?.value).toBeNull();
});
