import type {Environment,EventEnvelope} from '@automaktab/contracts';
export interface TrackerOptions{source:string;environment:Environment;endpoint:string;consent:boolean;fetch?:(url:string,options?:RequestInit)=>Promise<Response>;surface?:string;routes?:Record<string,string>;onStatus?:(status:{queued:number;dropped:number;lastReceiptId?:string})=>void;}
export interface Tracker{track:(name:string,properties:Record<string,unknown>)=>void;page:(path:string,referrer?:string)=>void;flush:()=>Promise<void>;setConsent:(granted:boolean)=>void;dispose:()=>void;}
const names=new Set(['page.view','feature.used','funnel.step','client.error']);
const keys=new Set(['path','surface','referrer','utm_source','utm_medium','utm_campaign','feature','goal','step','error_code']);
const safeSegments=new Set(['','pricing','about','contact','login','register','dashboard','schools','companies','branches','students','groups','attendance','payments','expenses','reports','settings','users','invoices','contracts','learning','lessons','tests','results','practice','quiz','blog','uz','ru','en','features','fleet','schedule','profile','leads','analytics','overview','traffic','acquisition','usage','funnels','courses','teachers','operators','vehicles','questions','training-programs','training-enrollments','driving-sessions','my-settlements','audit','fleet-map']);
function safePath(path:string,routes?:Record<string,string>):string{const bare=path.split(/[?#]/)[0]??'/';if(routes?.[bare])return routes[bare]!;return '/'+bare.split('/').filter(Boolean).slice(0,8).map(segment=>safeSegments.has(segment)?segment:':id').join('/');}
function safeReferrer(referrer:string):string|undefined{const hostPattern=/^(?=.{1,128}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/i;if(hostPattern.test(referrer))return referrer.toLowerCase();try{const url=new URL(referrer);return ['https:','http:'].includes(url.protocol)&&!url.username&&!url.password&&hostPattern.test(url.hostname)?url.hostname:undefined;}catch{return undefined;}}
function safeCampaign(value:string):boolean{return /^[a-z][a-z0-9_. -]{0,63}$/i.test(value)&&!/\d{5,}|[a-z0-9]{24,}|^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value)&&!/\d{7,}/.test(value.replace(/[_. -]/g,''));}
function trackingAllowed(){if(typeof navigator==='undefined')return true;return navigator.doNotTrack!=='1'&&!(navigator as Navigator&{globalPrivacyControl?:boolean}).globalPrivacyControl;}
export function createTracker(options:TrackerOptions):Tracker{
 let configured=false;try{const url=new URL(options.endpoint);const local=['localhost','127.0.0.1','[::1]'].includes(url.hostname);configured=(!local||options.environment==='synthetic')&&url.pathname==='/collect/v1/events'&&!url.username&&!url.password&&!url.search&&!url.hash&&(url.protocol==='https:'||(options.environment==='synthetic'&&url.protocol==='http:'&&local))&&/^[a-zA-Z0-9_.:-]{1,120}$/.test(options.source);}catch{configured=false;}
 const sender=options.fetch??((url:string,init?:RequestInit)=>fetch(url,init));let consent=options.consent;let disposed=false;let dropped=0;let queue:EventEnvelope[]=[];let inFlight:Promise<void>|undefined;let timer:ReturnType<typeof setTimeout>|undefined;let retryAfter=0;let anonymousId:string|undefined;let sessionId:string|undefined;let controller:AbortController|undefined;
 const notify=(receiptId?:string)=>{try{options.onStatus?.({queued:queue.length,dropped,...(receiptId?{lastReceiptId:receiptId}:{})});}catch{ /* telemetry status cannot interrupt its host */ }};
 const clearPrivateState=()=>{queue=[];anonymousId=undefined;sessionId=undefined;controller?.abort();if(timer)clearTimeout(timer);timer=undefined;retryAfter=0;notify();};
 const allowed=()=>configured&&consent&&trackingAllowed()&&!disposed;
 const flush=():Promise<void>=>{if(!trackingAllowed()){clearPrivateState();return Promise.resolve();}if(inFlight)return inFlight;if(!allowed()||!queue.length)return Promise.resolve();if(Date.now()<retryAfter){schedule();return Promise.resolve();}const batch=queue.slice(0,20);controller=new AbortController();const deadline=setTimeout(()=>controller?.abort(),5000);inFlight=(async()=>{try{const response=await sender(options.endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({events:batch}),credentials:'omit',referrerPolicy:'no-referrer',signal:controller?.signal,keepalive:true});if(response.status===429||response.status>=500){const seconds=Number(response.headers.get('Retry-After'));retryAfter=Date.now()+Math.min(Number.isFinite(seconds)&&seconds>0?seconds*1000:5000,60000);return;}if(response.status===400||response.status===413||response.status===403){const sent=new Set(batch.map(event=>event.event_id));dropped+=batch.length;queue=queue.filter(event=>!sent.has(event.event_id));notify();return;}if(response.status!==202){retryAfter=Date.now()+5000;return;}const envelope=await response.json() as {data?:{receiptId?:string;events?:{eventId:string;status:string}[]};receiptId?:string;events?:{eventId:string;status:string}[]};const result=envelope.data??envelope;if(!result.receiptId||!Array.isArray(result.events)){retryAfter=Date.now()+5000;return;}const sent=new Set(batch.map(event=>event.event_id));const resolved=new Set(result.events.filter(event=>sent.has(event.eventId)&&['accepted','duplicate','rejected'].includes(event.status)).map(event=>event.eventId));dropped+=result.events.filter(event=>sent.has(event.eventId)&&event.status==='rejected').length;queue=queue.filter(event=>!resolved.has(event.event_id));if(!resolved.size)retryAfter=Date.now()+5000;notify(result.receiptId);}catch{retryAfter=Date.now()+5000;notify();}finally{clearTimeout(deadline);controller=undefined;inFlight=undefined;if(queue.length)schedule();}})();return inFlight;};
 const schedule=()=>{if(timer||!allowed()||!queue.length)return;timer=setTimeout(()=>{timer=undefined;void flush();},Math.max(1000,retryAfter-Date.now()));};
 const track=(name:string,properties:Record<string,unknown>)=>{try{if(!trackingAllowed()){clearPrivateState();return;}if(!allowed()||!names.has(name))return;const clean:Record<string,string>={};for(const [key,value]of Object.entries(properties)){if(!keys.has(key))continue;if(typeof value!=='string')continue;if(key==='path')clean[key]=safePath(value,options.routes);else if(key==='referrer'){const host=safeReferrer(value);if(host)clean[key]=host;}else if(key.startsWith('utm_')){if(safeCampaign(value))clean[key]=value;}else if(/^[a-zA-Z0-9_.:/ -]{1,128}$/.test(value)&&!/[?#@]/.test(value))clean[key]=value;}
  if(!Object.keys(clean).length)return;if(!anonymousId)anonymousId=crypto.randomUUID();if(!sessionId)sessionId=crypto.randomUUID();if(queue.length>=100){queue.shift();dropped++;}queue.push({event_id:crypto.randomUUID(),schema_version:1,name,occurred_at:new Date().toISOString(),source:options.source,environment:options.environment,anonymous_id:anonymousId,session_id:sessionId,properties:clean});notify();schedule();
 }catch{ /* instrumentation must never break sign-in or product actions */ }};
 return {track,page:(path,referrer)=>track('page.view',{path,surface:options.surface??options.source,...(referrer?{referrer}:{})}),flush,setConsent:(granted)=>{consent=granted;if(!granted)clearPrivateState();},dispose:()=>{disposed=true;clearPrivateState();}};
}
